Mvc5MobileApplicationSG/Controllers/PDAController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mvc5MobileApplicationSG.Models;

namespace Mvc5MobileApplicationSG.Controllers
{
    public class PDAController : Controller
    {

        public static string ABN = "TESTDB";


        public ActionResult mainPage()
        {
            MenuRetievalModel model = new MenuRetievalModel();
            model.ABN = ABN;
            model.alertmessage = "";
            Session["model"] = model;
            ViewBag.ErrorMessage = "";
            model.getCategories();
            return View("mainPage", model);
        }

        public ActionResult mainPageSession()
        {
            MenuRetievalModel model = (MenuRetievalModel)Session["model"];
            model.getCategories();
            return View("mainPage", model);
        }

        public ActionResult getDeliveryItem()
        {


            MenuRetievalModel model = (MenuRetievalModel)Session["model"];

            if (!model.getDeliveryOn())
            {
                return View("deliveryOffline");
            }

            model.getCategories();
            return PartialView("getMenuOrder", model);



        }



        public ActionResult getMenuCatItem()
        {

            MenuRetievalModel model = (MenuRetievalModel)Session["model"];

            return PartialView("getMenuOrder", (MenuRetievalModel)Session["model"]);

        }


        [HttpPost]
        public ActionResult createOrder(MenuRetievalModel model)
        {

            ((MenuRetievalModel)Session["model"]).name = model.name;
            ((MenuRetievalModel)Session["model"]).phone = model.phone;
            ((MenuRetievalModel)Session["model"]).address = model.address;
            ((MenuRetievalModel)Session["model"]).itemno = model.itemno; //suburb


            Session["orderdate"] = ((MenuRetievalModel)Session["model"]).createOrder("homedelivery");

            return PartialView("getMenuOrder", (MenuRetievalModel)Session["model"]);
        }

        [HttpPost]
        public ActionResult createTakeAway(MenuRetievalModel model)
        {


            ((MenuRetievalModel)Session["model"]).name = model.name;
            ((MenuRetievalModel)Session["model"]).phone = model.phone;

            Session["orderdate"] = ((MenuRetievalModel)Session["model"]).createOrderTA("takeaway");


            return PartialView("getMenuOrder", (MenuRetievalModel)Session["model"]);
        }

        public ActionResult updateQty(String itemno, String func)
        {

            ItemModel found = new ItemModel();
            MenuRetievalModel model = (MenuRetievalModel)Session["model"];
            
                found.itemno = itemno;
                int signal = 0;
                if (func == "add")
                {
                   
                    signal = 1;

                }
                else if (func == "deduct")
                {
                  
                    signal = -1;

                }
                model.transferItems(found, signal);
                model.recallDetails();

                return PartialView("paymentdialog", model);


        }

        public ActionResult refreshModel()
        {
            if (Session["model"] != null)
            {
                MenuRetievalModel model = (MenuRetievalModel)Session["model"];
                model.recallDetails();

            }

            return getMenuCatItem();
        }

        public void updateItemCode(String itemcode)
        {

            if (Session["model"] != null)
            {

                MenuRetievalModel model = (MenuRetievalModel)Session["model"];

                model.itemno = itemcode;


            }


        }


        [HttpPost]
        public ActionResult pay(MenuRetievalModel model)
        {
            model.ABN = ((MenuRetievalModel)Session["model"]).ABN;
            Session["model"] = model;
            model.orderdate = (DateTime)Session["orderdate"];
            model.pay("enter here");

            if (model.approved == "APPROVED")
            {
                if (((MenuRetievalModel)Session["model"]).OrderType == "takeaway")
                {
                    return PartialView("paid", model);
                }
                else
                {
                    return PartialView("paiddelivery", model);

                }
            }
            else
            {
                model.cardnumber = "";
                model.cardexpiry = "";
                model.cardcvv = "";
                return PartialView("declined", model);

            }

        }

        public ActionResult approved()
        {
            if (((MenuRetievalModel)Session["model"]).OrderType == "takeaway")
            {
                return PartialView("paid");
            }
            else
            {
                return PartialView("paiddelivery");

            }
        }

        public ActionResult declined()
        {

            return PartialView("declined");
        }

        public ActionResult expired()
        {

            return PartialView("expiredSession");

        }

        public ActionResult getShoppingCart()
        {

            return PartialView("ViewShoppingCart", (MenuRetievalModel)Session["model"]);

        }

        [HttpPost]
        public ActionResult forceModify(MenuRetievalModel model)
        {

            model.name = ((MenuRetievalModel)Session["model"]).name;
            model.phone = ((MenuRetievalModel)Session["model"]).phone;
            model.address = ((MenuRetievalModel)Session["model"]).address;
            model.itemno = ((MenuRetievalModel)Session["model"]).itemno; //suburb
            model.actualitemno = ((MenuRetievalModel)Session["model"]).itemno; //suburb
            model.Categories = ((MenuRetievalModel)Session["model"]).Categories;
            model.orderdate = (DateTime)Session["orderdate"];
            model.OrderType = ((MenuRetievalModel)Session["model"]).OrderType;
            model.ABN = ((MenuRetievalModel)Session["model"]).ABN;
            model.DataSetModifiers = ((MenuRetievalModel)Session["model"]).DataSetModifiers;
            Session["model"] = model;
            ModifierModel modon = model.GetNameOfModifierOn();
            model.forceModify(modon.BtnDesc, Convert.ToDecimal(modon.price));

            model.recallDetails();
            
            return PartialView("paymentdialog", (MenuRetievalModel)Session["model"]);
        }

        [HttpGet]
        public ActionResult getForceModfier(String itemno)
        {
            ((MenuRetievalModel)Session["model"]).itemno = itemno;
            ((MenuRetievalModel)Session["model"]).actualitemno = itemno;
            return PartialView("forceModify", (MenuRetievalModel)Session["model"]);

        }

        [HttpGet]
        public ActionResult getModifiers(String itemno, String actualitemno)
        {
            ((MenuRetievalModel)Session["model"]).itemno = itemno;
            ((MenuRetievalModel)Session["model"]).actualitemno = actualitemno;
            return PartialView("modify", (MenuRetievalModel)Session["model"]);

        }

        [HttpPost]
        public ActionResult modify(MenuRetievalModel model)
        {

            model.name = ((MenuRetievalModel)Session["model"]).name;
            model.phone = ((MenuRetievalModel)Session["model"]).phone;
            model.address = ((MenuRetievalModel)Session["model"]).address;
            model.Categories = ((MenuRetievalModel)Session["model"]).Categories;
            model.orderdate = (DateTime)Session["orderdate"];
            model.OrderType = ((MenuRetievalModel)Session["model"]).OrderType;
            model.ABN = ((MenuRetievalModel)Session["model"]).ABN;
            model.DataSetModifiers = ((MenuRetievalModel)Session["model"]).DataSetModifiers;
            Session["model"] = model;

            ModifierModel modon = model.GetNameOfModifierOn();
            model.forceModify(modon.BtnDesc, Convert.ToDecimal(modon.price));

            model.recallDetails();
            
            return PartialView("paymentdialog", (MenuRetievalModel)Session["model"]);
        }


    }
}

Mvc5MobileApplicationSG/Views/PDA/ViewShoppingCart.cshtml
@model Mvc5MobileApplicationSG.Models.MenuRetievalModel


<button onclick="recallbill('@Model.name');">Shopping Cart</button>
<hiddenbutton id="paymentbutton" style="display: none;" data-toggle="modal" data-target="#paymentsummarymodal" onclick="'@Model.recallDetails()'" />

Mvc5MobileApplicationSG/Views/PDA/declined.cshtml
@model Mvc5MobileApplicationSG.Models.MenuRetievalModel

@{
    ViewBag.Title = "declined";
}

<h3 style="color: red;">DECLINED</h3>

@if (@Model.approved == null || @Model.approved != "APPROVED")
{
    <label for="cardnumber" style="width:80px">Card number:</label>
    @Html.TextBoxFor(m => m.cardnumber, new { @required = "required" })
    <br />
    <label for="cardexpiry" style="width:80px">Card expiry date:</label>
    @Html.TextBoxFor(m => m.cardexpiry, new { @required = "required" })
    <br />
    <label for="cardcvv" style="width:80px">Card cvv number:</label>
    @Html.TextBoxFor(m => m.cardcvv, new { @required = "required" })
    <br />
    <br />
    <input id="submitpayment" style="width: 60px; height: 25px; font-size: 10px"  type="submit" value="Pay Card">
    <button id="paymentclose" style="width: 60px; height: 25px; font-size: 10px" type="button" class="btn btn-default" data-dismiss="modal">Back</button>
    
}

Mvc5MobileApplicationSG/Views/PDA/deliveryOffline.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>

    <script>

    function home() {
        // Now add markers
        var url = '@Url.Action("mainPage", "Home")'
        window.location = url;

    }

    </script>

</head>
<body>
    <div>
        <h1>Online Delivery is currently offline, please try again later on opening hours (see Contact page for details) 
            or call (02) 6296 3111 to make your order</h1>

        <button style="font-size: 15px;" onclick="home();">Back</button>



    </div>
</body>
</html>

Mvc5MobileApplicationSG/Views/PDA/expiredSession.cshtml
@{
    ViewBag.Title = "expiredSession";
}

<script>

    function home() {
        // Now add markers
        var url = '@Url.Action("mainPage", "Home")'
        window.location = url;

    }

</script>

<body style="background-color: green;">

    <h1>Your session at Spring Gardens Website has expired.</h1>

    <button style="font-size: 15px;" onclick="home();">Spring Gardens Home Page</button>

</body>

Mvc5MobileApplicationSG/Views/PDA/forceModify.cshtml
@model Mvc5MobileApplicationSG.Models.MenuRetievalModel
        
    
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                </div>
                <div class="modal-body">
                    @if (!Model.getDeliveryOn())
                    {
                        <h1>Cloud Service Currently Offline please try again later. Please refresh your internet browser when trying again by closing and reopening this page.</h1>

                        <button id="hdclose" type="button" class="btn btn-default" data-dismiss="modal">Close</button>

                    }
                    else
                    {
                        using (Ajax.BeginForm("forceModify", "PDA", null, new AjaxOptions { HttpMethod = "Post", UpdateTargetId = "items", OnSuccess = "OnSuccessModify" }, null))
                        {

                            <div id="deliverycontent">
                                <h4 class="modal-title">Force Modify</h4>

                                <p>Please enter details</p>
                                @for (int i = 0; i < Model.CurrentItemSelected().Modifiermodels.Count; i++)
                                {

                                    if (@Model.CurrentItemSelected().Modifiermodels[i].forced == "Y")
                                    {
                                        <label for="name">@Model.CurrentItemSelected().Modifiermodels[i].BtnDesc</label>
                                        @Html.RadioButtonFor(m => m.modBtnDesc, @Model.CurrentItemSelected().Modifiermodels[i].BtnDesc, new { @id = "radiobutton" })
                                    }


                                }

                            </div>
                            <br />
                            <input id="submitmodify" type="submit" value="Done" data-toggle="modal" data-target="#forcedmodifiermodal" />
                           
                            <br />


                        }

                    }
                </div>
            </div>



        </div>

Mvc5MobileApplicationSG/Views/PDA/getMenuOrder.cshtml
@model Mvc5MobileApplicationSG.Models.MenuRetievalModel

@{
    ViewBag.Title = "getMenuOrder";

}

<script>


    $(document).ready(function () {
        $('#items').validate({
            rules: {
                cardnumber: "required",

                cardexpiry: "required",

                cardcvv: "required"
            }
        });
    });


</script>

@if (@Model != null)
{


    if (Model.name != null && Model.name != "")
    {

        <hiddenbutton id="paymentbutton" style="display: none;" data-toggle="modal" data-target="#paymentsummarymodal" />
        <hiddenbutton id="forcedModifybutton" style="display: none;" data-toggle="modal" data-target="#forcedmodifiermodal"/>
        <button onclick="recallbill('@Model.name');" id="myBtn" title="Go to top">Go to Shopping Cart</button>

    }



    <div class="container">
        <!-- Modal -->
        <div id="createdmodal" class="modal" data-backdrop="static" data-keyboard="false" role="dialog">
            <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <h2>Order has been created please start selecting your items.</h2>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Ok</button>
                    </div>

                </div>
            </div>

        </div>
    </div>

    <div style="width:90%;align-items:center;font-size:15px;margin-left:5%">



        @if (Model != null && Model.Categories != null)
        {


            if (Model.name != null && Model.name != "")
            {
                for (int i = 0; i < Model.Categories.Count; i++)
                {
                    var categories = Model.Categories;
                    <a onclick="myFunction('@categories[i].catno.Trim()')" class="w3-btn w3-block w3-black" style="font-size: 15px">@categories[i].description.Trim()</a>

                    <div id=@Model.Categories[i].catno.Trim() class="w3-block w3-hide">


                        @{
                            var groups = categories[i].getGroups();
                            for (int j = 0; j < groups.Count; j++)
                            {

                                <a onclick="myFunction('@groups[j].grpno')" class="w3-btn w3-block" style="font-size: 15px;background-color: lightgrey;">@groups[j].description</a>

                                <div id=@groups[j].grpno class="w3-block w3-hide" style="font-size: 10px; color: black;">
                                    <ul>
                                        @for (int k = 0; k < groups[j].ItemModels.Count; k++)
                                        {

                                        <li class="no-bullet">
                                            <button id=@groups[j].ItemModels[k].getaddbuttonstr() style="align-self:center; font-size: 10px; color: white; background: green;" onclick="return forceModify('@groups[j].ItemModels[k].itemno', '@groups[j].ItemModels[k].getinputboxstr()', '@groups[j].ItemModels[k].nostock')"> + </button>
                                            <input id=@groups[j].ItemModels[k].getinputboxstr() style="width: 30px; font-size: 10px; color: black;" value="0" disabled />
                                            @groups[j].ItemModels[k].itemlongname - $@String.Format("{0:#.00}", @groups[j].ItemModels[k].itemprice)
                                            
                                        </li>


                                        }
                                    </ul>
                                </div>

                            }
                        }


                    </div>
                }
            }
            else
            {

                for (int i = 0; i < Model.Categories.Count; i++)
                {
                    var categories = Model.Categories;
                    <a onclick="myFunction('@categories[i].catno.Trim()')" class="w3-btn w3-block w3-black" style="font-size: 15px">@categories[i].description.Trim()</a>

                    <div id=@Model.Categories[i].catno.Trim() class="w3-block w3-hide">


                        @{
                            var groups = categories[i].getGroups();
                            for (int j = 0; j < groups.Count; j++)
                            {

                                <a onclick="myFunction('@groups[j].grpno')" class="w3-btn w3-block" style="font-size: 15px;background-color: lightgrey;">@groups[j].description</a>

                                <div id=@groups[j].grpno class="w3-block w3-hide">

                                    @for (int k = 0; k < groups[j].ItemModels.Count; k++)
                                    {

                                        <a onclick="myFunction('@groups[j].ItemModels[k].itemno')" class="w3-btn w3-block" style="font-size: 10px;background-color: white;">@groups[j].ItemModels[k].itemlongname</a>

                                        <div id=@groups[j].ItemModels[k].itemno class="w3-block w3-hide">
                                            <h4>Information</h4>
                                            <p>@groups[j].ItemModels[k].description</p>
                                            <br />
                                            <h4>Dietry Requirements</h4>
                                            <p>@groups[j].ItemModels[k].dietry</p>
                                            <br />
                                            <h4>Price: $@String.Format("{0:#.00}", @groups[j].ItemModels[k].itemprice)</h4>

                                        </div>

                                    }

                                </div>

                            }
                        }


                    </div>
                }


            }

        }

    </div>

}

Mvc5MobileApplicationSG/Views/PDA/modify.cshtml
@model Mvc5MobileApplicationSG.Models.MenuRetievalModel
        
    
      
                    @if (!Model.getDeliveryOn())
                    {
                        <h1>Cloud Service Currently Offline please try again later. Please refresh your internet browser when trying again by closing and reopening this page.</h1>

                        <button id="hdclose" type="button" class="btn btn-default" data-dismiss="modal">Close</button>

                    }
                    else
                    {
                        using (Ajax.BeginForm("modify", "PDA", null, new AjaxOptions { HttpMethod = "Post", UpdateTargetId = "items", OnSuccess = "OnSuccessModify" }, null))
                        {

<div id="deliverycontent">

    @if (@Model.CurrentItemSelected() != null)
    {
        @Html.DropDownListFor(m => m.modBtnDesc, @Model.CurrentItemSelected().getNonForcedModifiers(), new { @id = "modcode" })
        @Html.HiddenFor(m => m.itemno, @Model.itemno)
        @Html.HiddenFor(m => m.actualitemno, @Model.actualitemno)

    }

</div>
                            <br />
                            <input id="submitmodifyitem" type="submit" value="Add" data-toggle="modal" data-target="#modifiermodal"/>
                            <button type="button" data-toggle="modal" data-target="#modifiermodal"> Close </button>
                            <br />


                        }

                    }
               

Mvc5MobileApplicationSG/Views/PDA/paid.cshtml
@model Mvc5MobileApplicationSG.Models.MenuRetievalModel

@{
    ViewBag.Title = "paid";
}
<script>

    function refresh() {

        var url = '@Url.Action("mainPage", "GarysKitchen")';

        window.location = url;

    }

</script>

<body>

   
    <h3>Your Order has been successfully paid, deliveries will be delivered within the 1 hour, pickups ready in 15 - 20 mins</h3>

        <button id="paymentsuccessclose" onclick="refresh();" type="button" class="btn btn-default" data-dismiss="modal">Close</button>



</body>

Mvc5MobileApplicationSG/Views/PDA/paiddelivery.cshtml
@model Mvc5MobileApplicationSG.Models.MenuRetievalModel

@{
    ViewBag.Title = "paid";
}
<script>

    function refresh() {

        var url = '@Url.Action("mainPage", "GarysKitchen")';

        window.location = url;

    }

</script>

<body>

    <h3>Your Order has been successfully paid, deliveries will be delivered within the 1 hour, pickups ready in 15 - 20 mins</h3>

   <button id="paymentsuccessclose" onclick="refresh();" type="button" class="btn btn-default" data-dismiss="modal">Close</button>

</body>

Mvc5MobileApplicationSG/Views/PDA/paymentdialog.cshtml
@model Mvc5MobileApplicationSG.Models.MenuRetievalModel

@{
    ViewBag.Title = "paymentdialog";
}

<script>

    function paymentclick() {
        if ($("#cardid").val() == "") {
            alert("card number field required");
            return false;
        }

        if ($("#dateid").val() == "") {
            alert("expiry date field required");
            return false;
        }

        if ($("#cvvid").val() == "") {
            alert("cvv field required");
            return false;
        }


        return true;


    }


</script>

@using (@Ajax.BeginForm("pay", "PDA", null, new AjaxOptions { HttpMethod = "Post", UpdateTargetId = "paymentdiv" }, new { @id = "paymentform" }))
{
<div id="total" style="left: initial; margin-left: 1%">

    @{
        double total = 0;
        var suburb = "";

        if (Model != null && Model.RecallItems != null)
        {
        <ul>
            @for (int i = 0; i < Model.RecallItems.Count; i++)
            {

                if (Model.RecallItems[i].discountflag == null || Model.RecallItems[i].discountflag == "" || Model.RecallItems[i].discountflag == "N")
                {

                    if (!@Model.RecallItems[i].itemname.Trim().StartsWith("("))
                    {
            <li style="font-size: 10px">
                <button style="align-self:center; font-size: 10px; color: white; background: green;" onclick="return updateQty('add', '@Model.RecallItems[i].getinputboxstr()', '@Model.RecallItems[i].itemno')">+</button>&nbsp;<button style="align-self:center; font-size: 10px; color: white; background: green;" onclick="return updateQty('deduct', '@Model.RecallItems[i].getinputboxstr()', '@Model.RecallItems[i].itemno')">-</button> @Model.RecallItems[i].itemqty X $@String.Format("{0:0.00}", @Math.Round(@Model.RecallItems[i].itemprice, 2)) @Model.RecallItems[i].itemname.Trim().ToUpper()
               
                
                @if (@Model.CurrentItemSelected(@Model.RecallItems[i].actualitemno).getNonForcedModifiers().Count() > 0 && @Model.RecallItems[i].itemqty == 1)
                {
                    <button type="button" style="align-self:center; font-size: 10px; color: white; background: green;" onclick="return modify('@Model.RecallItems[i].itemno', '@Model.RecallItems[i].actualitemno')"> Modify </button>
                    <hiddenbutton type="button" id="modifybutton" data-toggle="modal" data-target="#modifiermodal"></hiddenbutton>
                }

            </li>

                    }
                    else
                    {
                        <li style="font-size: 10px">
                            @Model.RecallItems[i].itemqty X $@String.Format("{0:0.00}", @Math.Round(@Model.RecallItems[i].itemprice, 2)) @Model.RecallItems[i].itemname.Trim().ToUpper()
                        </li>
                    }

                    <br />
                }
                else
                {
                    suburb = @Model.RecallItems[i].itemname.Trim() + " at " + "$" + @String.Format("{0:0.00}", @Math.Round(@Model.RecallItems[i].itemprice, 2));

                }



                total = total + @Model.RecallItems[i].itemqty * @Model.RecallItems[i].itemprice;
            }
        </ul>
        <p>---------------------------------------------</p>
        <h5>@suburb</h5>

        <h2>Sub Total: $@String.Format("{0:0.00}", @Math.Round(total, 2))</h2>
        <p>---------------------------------------------</p>
    }
    else
    {
    <h3>No Items Selected Yet</h3>
    }

    }

    @Html.HiddenFor(m => m.subtotal, new { @Value = @Math.Round(total, 2) })


    @if ((total >= 30 && Model.OrderType == "homedelivery") || Model.OrderType == "takeaway")
    {
        <div id="paymentdiv">

            @if (@Model.approved == null || @Model.approved != "APPROVED")
            {
                <label for="cardnumber" style="width:80px">Card number:</label>
                @Html.TextBoxFor(m => m.cardnumber, new { @id = "cardid" })
                <br />
                <label for="cardexpiry" style="width:80px">Card expiry date:</label>
                @Html.TextBoxFor(m => m.cardexpiry, new { @id = "dateid" })
                <h5>*enter the slash between the day and month e.g 09/10</h5>
                <br />
                <label for="cardcvv" style="width:80px">Card cvv number:</label>
                @Html.TextBoxFor(m => m.cardcvv, new { @id = "cvvid" })
                <br />


            }
            <br />
            <input id="submitpayment" style="width: 60px; height: 25px; font-size: 10px" type="submit" value="Pay Card" onclick="return paymentclick();">
            <button id="paymentclosedialog" type="button" class="btn btn-default" data-dismiss="modal">Back</button>
        </div>

    }
    else
    {
        <h3>Home delivery orders must be minimum $30</h3>
        <button id="paymentclosedialog" type="button" class="btn btn-default" data-dismiss="modal">Back</button>

    }



    <br />
</div>


}