Mvc5MobileApplicationSG/Controllers/SpringGardenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mvc5MobileApplicationSG.Models;
using Stripe;

namespace Mvc5MobileApplicationSG.Controllers
{
    public class SpringGardenController : Controller
    {

        public static string ABN = "67645919268";
        //  protected static string acctid = "acct_1H1m8RHiZX8NuuLN";

        protected static string acctid = "acct_1H1ModHiCRtkZvz2";


        public ActionResult About()
        {
            ViewBag.Message = "Your app description page.";

            return PartialView("About");
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return PartialView("Contact");
        }

        public ActionResult mainPage()
        {

            return View("Unavailable");

            /*
            MenuRetievalModel model = new MenuRetievalModel();
            model.ABN = ABN;
            model.alertmessage = "";
            Session["model"] = model;
            ViewBag.ErrorMessage = "";
            model.getCategories();
            return View("mainPage", model);

            */

        }

        public ActionResult mainPageSession()
        {
            MenuRetievalModel model = (MenuRetievalModel)Session["model"];
            model.getCategories();
            return View("mainPage", model);
        }

        public ActionResult getDeliveryItem()
        {


            MenuRetievalModel model = (MenuRetievalModel)Session["model"];

            if (!model.getDeliveryOn())
            {
                return View("deliveryOffline");
            }

            model.getCategories();
            return PartialView("getMenuOrder", model);



        }

        [HttpGet]
        public ActionResult validateContact(String email, String cashcard)
        {


            ((MenuRetievalModel)Session["model"]).email = email;
            ((MenuRetievalModel)Session["model"]).Notes = cashcard;

            Session["id"] = ((MenuRetievalModel)Session["model"]).generateID();
            ((MenuRetievalModel)Session["model"]).updateContact();

            ViewBag.Invalid = "";

            return PartialView("validateContact", (MenuRetievalModel)Session["model"]);


        }

        [HttpGet]
        public ActionResult validateContactBooking(MenuRetievalModel model)
        {

            ((MenuRetievalModel)Session["model"]).BookingTable = model.BookingTable;
            ((MenuRetievalModel)Session["model"]).email = model.email;
            ((MenuRetievalModel)Session["model"]).OrderType = "booking";
            createBooking((MenuRetievalModel)Session["model"]);
            Session["id"] = ((MenuRetievalModel)Session["model"]).generateID();
            ((MenuRetievalModel)Session["model"]).updateContact();


            ViewBag.Invalid = "";
            ((MenuRetievalModel)Session["model"]).ProgressToBookingConfirmation = true;
            return PartialView("validateContact", (MenuRetievalModel)Session["model"]);


        }

        [HttpGet]
        public ActionResult validateBooking(String id)
        {

            if (id == Session["id"].ToString())
            {

                ((MenuRetievalModel)Session["model"]).confirmedcontact();
                return PartialView("confirmedbooking", (MenuRetievalModel)Session["model"]);


            }
            else
            {
                ViewBag.Invalid = "Invalid Pin, Please try again";
                return PartialView("validateContact", (MenuRetievalModel)Session["model"]);


            }



        }

        [HttpGet]
        public ActionResult validateDetails(String id, String ordertype)
        {

            if (id == Session["id"].ToString())
            {
                if (ordertype == "homedelivery")
                {
                    return PartialView("delivery", (MenuRetievalModel)Session["model"]);

                }
                else if (ordertype == "takeaway")
                {

                    return PartialView("takeawaydialog", (MenuRetievalModel)Session["model"]);

                }
                else
                {

                    return PartialView("bookingdialog", (MenuRetievalModel)Session["model"]);

                }
            }
            else
            {
                ViewBag.Invalid = "Invalid Pin, Please try again";
                return PartialView("validateContact", (MenuRetievalModel)Session["model"]);


            }



        }



        [HttpGet]
        public ActionResult validate(String id)
        {

            if (id == Session["id"].ToString())
            {
                ((MenuRetievalModel)Session["model"]).confirmedcontact();
                return PartialView("paid", (MenuRetievalModel)Session["model"]);


            }
            else
            {
                ViewBag.Invalid = "Invalid Pin, Please try again";
                return PartialView("validateContact", (MenuRetievalModel)Session["model"]);


            }



        }


        [HttpGet]
        public ActionResult findContactBooking(String phone)
        {
            if (Session["model"] == null)
            {
                refreshsession();

            }

            ((MenuRetievalModel)Session["model"]).OrderType = "booking";

            ((MenuRetievalModel)Session["model"]).bookingrequest = true;

            ((MenuRetievalModel)Session["model"]).phonesearch = phone;

            ((MenuRetievalModel)Session["model"]).findcontactBooking(phone);

            if (((MenuRetievalModel)Session["model"]).email != null && ((MenuRetievalModel)Session["model"]).email.Trim() != "")
            {
                Session["id"] = ((MenuRetievalModel)Session["model"]).generateID();


                return PartialView("validateContact", (MenuRetievalModel)Session["model"]);

            }

            return PartialView("bookingdialog", ((MenuRetievalModel)Session["model"]));


        }

        [HttpGet]
        public ActionResult findContactTA(String phone)
        {
            if (Session["model"] == null)
            {
                refreshsession();

            }

            ((MenuRetievalModel)Session["model"]).OrderType = "takeaway";

            ((MenuRetievalModel)Session["model"]).phonesearch = phone;

            ((MenuRetievalModel)Session["model"]).findcontactTA(phone, "takeaway");

            if (((MenuRetievalModel)Session["model"]).email != null && ((MenuRetievalModel)Session["model"]).email.Trim() != "")
            {
                Session["id"] = ((MenuRetievalModel)Session["model"]).generateID();


                return PartialView("validateContact", (MenuRetievalModel)Session["model"]);

            }

            return PartialView("takeawaydialog", ((MenuRetievalModel)Session["model"]));


        }


        [HttpGet]
        public ActionResult findContactDelivery(String phone)
        {
            if (Session["model"] == null)
            {
                refreshsession();

            }

            ((MenuRetievalModel)Session["model"]).OrderType = "homedelivery";

            ((MenuRetievalModel)Session["model"]).phonesearch = phone;

            ((MenuRetievalModel)Session["model"]).findcontact(phone, "homedelivery");

            if (((MenuRetievalModel)Session["model"]).email != null && ((MenuRetievalModel)Session["model"]).email.Trim() != "")
            {
                Session["id"] = ((MenuRetievalModel)Session["model"]).generateID();


                return PartialView("validateContact", (MenuRetievalModel)Session["model"]);

            }

            return PartialView("delivery", ((MenuRetievalModel)Session["model"]));


        }


        public ActionResult getMenuCatItem()
        {

            if (Session["model"] == null)
            {
                refreshsession();

            }
            MenuRetievalModel model = (MenuRetievalModel)Session["model"];

            return PartialView("getMenuOrder", (MenuRetievalModel)Session["model"]);

        }


        [HttpGet]
        public ActionResult getSearchDialog(String ordertype)
        {
            if (Session["model"] == null)
            {
                refreshsession();

            }


            ((MenuRetievalModel)Session["model"]).OrderType = ordertype;

            return PartialView("search", (MenuRetievalModel)Session["model"]);


        }


        [HttpGet]
        public ActionResult getSearchDialogBooking()
        {
            if (Session["model"] == null)
            {
                refreshsession();

            }


            ((MenuRetievalModel)Session["model"]).OrderType = "booking";

            return PartialView("search", (MenuRetievalModel)Session["model"]);


        }



        [HttpGet]
        public ActionResult getBookingDialog()
        {
            if (Session["model"] == null)
            {
                refreshsession();

            }

            ((MenuRetievalModel)Session["model"]).ProgressToBookingTable = false;
            ((MenuRetievalModel)Session["model"]).ProgressToBookingConfirmation = false;
            return PartialView("bookingdialog", (MenuRetievalModel)Session["model"]);


        }

        [HttpGet]
        public ActionResult getDeliveryDialog()
        {
            if (Session["model"] == null)
            {
                refreshsession();

            }

            ((MenuRetievalModel)Session["model"]).confirmDetails = false;
            ((MenuRetievalModel)Session["model"]).noDetails = true;
            ((MenuRetievalModel)Session["model"]).ProgressToBookingConfirmation = false;
            return PartialView("delivery", (MenuRetievalModel)Session["model"]);


        }

        public void refreshsession()
        {

            Session["model"] = new MenuRetievalModel();
            ((MenuRetievalModel)Session["model"]).ABN = ABN;
            ((MenuRetievalModel)Session["model"]).getCategories();

        }


        [HttpPost]

Mvc5MobileApplicationSG/Views/SpringGarden/Unavailable.cshtml
<h1>This site is no longer available</h1>

Mvc5MobileApplicationSG/Views/SpringGarden/ViewShoppingCart.cshtml
@model Mvc5MobileApplicationSG.Models.MenuRetievalModel


<button onclick="recallbill('@Model.name');">Shopping Cart</button>
<hiddenbutton id="paymentbutton" style="display: none;" data-toggle="modal" data-target="#paymentsummarymodal" onclick="'@Model.recallDetails()'" />

Mvc5MobileApplicationSG/Views/SpringGarden/confirmedbooking.cshtml
@model Mvc5MobileApplicationSG.Models.MenuRetievalModel

@{
    ViewBag.Title = "bookingconfirmed";
}
<script>

    function refresh() {

        var url = '@Url.Action("mainPage", "SpringGarden")';

        window.location = url;

    }

</script>

<body>

    <h3>Your booking has been successfully confirmed</h3>

   <button id="bookingsuccessclose" onclick="refresh();" type="button" class="btn btn-default" data-dismiss="modal">Close</button>

</body>

Mvc5MobileApplicationSG/Views/SpringGarden/declined.cshtml
@model Mvc5MobileApplicationSG.Models.MenuRetievalModel

@{
    ViewBag.Title = "declined";
}

<h3 style="color: red;">DECLINED</h3>

@if (@Model.approved == null || @Model.approved != "APPROVED")
{
    <label for="cardnumber" style="width:80px">Card number:</label>
    @Html.TextBoxFor(m => m.cardnumber, new { @required = "required" })
    <br />
    <label for="cardmonth" style="width:80px">Card expiry date:</label>
    @Html.DropDownListFor(m => m.cardexpirymonth, Model.MonthList, new { @id = "cardexpirymonthid" })
    @Html.DropDownListFor(m => m.cardexpiryyear, Model.YearList, new { @id = "cardexpiryyearid" })
    <p> (Month/Year)</p>
    <br />
    <label for="cardcvv" style="width:80px">Card cvv number:</label>
    @Html.TextBoxFor(m => m.cardcvv, new { @required = "required" })
    <br />

}
<br />
<div id="processing" style="display: none"><h5>processing please wait...</h5></div>
<button id="submitpayment" style="width: 100px; float: left;" class="btn btn-default" type="submit" onclick="return paymentclick();">Pay Card</button>
<button id="paymentclosedialog" style="width: 100px; float: right;" type="button" class="btn btn-default" data-dismiss="modal">Back</button>

Mvc5MobileApplicationSG/Views/SpringGarden/delivery.cshtml
@model Mvc5MobileApplicationSG.Models.MenuRetievalModel

@{
    ViewBag.Title = "delivery";
}

<script>

     function createOrder() {


            var url = '@Url.Action("createOrderNonModel", "SpringGarden")';
            var name = document.getElementById("nameid").value;
            var phone = document.getElementById("phoneid").value;
            var address = document.getElementById("addressid").value;
         var suburb = document.getElementById("suburbid").value;

         if (String(name) == "") {
             alert("Name required");
             return;


         }

         if (String(phone) == "") {
             alert("Phone required");
             return;


         }

         if (String(address) == "") {
             alert("Address required");
             return;


         }

         if (String(suburb) == "") {
             alert("Suburb required");
             return;


         }


            $.ajax({
                url: url,
                type: "POST",
                data: { name: name, phone: phone, address: address, itemno: suburb },
                success: function (results) {
                    $("#tabs-1").html(results);
                    OnSuccess();
                    var closebutton = document.getElementById("hdclose");
                    closebutton.click();
                },


            });

            return false;
    }




</script>

@if (Model.email == null || Model.email.Trim() == "")
{

    <h1>Cannot find details</h1>
    <div class="w3-container" id="deliverycontent">
        <h4 class="modal-title">Delivery</h4>

        <p>Please enter details</p>
        <label for="name">Name:</label>
        <input id="nameid" class="w3-input" type="text" value="">

        <br />
        <label for="name">Phone:</label>
        <input id="phoneid" class="w3-input" type="text" value="">
        <br />
        <label for="name">Address:</label>
        <input id="addressid" class="w3-input" type="text" value="">
        <br />
        <label for="name">Suburb (mandatory*):</label>
        @if (@Model.TransferItems != null)
        {
            @Html.DropDownListFor(m => m.itemno, Model.TransferItems, new { @id = "suburbid", style = "width: 200px; height: 30px" })

        }
        <br />
    </div>
    <br />
    <input id="submithd" onclick="createOrder();" style="width: 120px; float: left;" type="button" value="Create Order">
    <button id="hdclose" onclick="showStuff(document.getElementById('tabs1'));" style="width: 120px; float: right;" type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <br />
}
else
{

    <div class="w3-container" id="deliverycontent">
        <h4 class="modal-title">Delivery</h4>

        <p>Please enter details</p>
        <label for="name">Name:</label>
        <input id="nameid" class="w3-input" type="text" value="@Model.name">

        <br />
        <label for="name">Phone:</label>
        <input id="phoneid" class="w3-input" type="text" value="@Model.phone">
        <br />
        <label for="name">Address:</label>
        <input id="addressid" class="w3-input" type="text" value="@Model.address">
        <br />
        <label for="name">Suburb (mandatory*):</label>
        @if (@Model.TransferItems != null)
        {
            @Html.DropDownListFor(m => m.itemno, Model.TransferItems, new { @id = "suburbid", style = "width: 200px; height: 30px" })

        }
        <br />
    </div>
    <br />
    <input id="submithd" onclick="createOrder();" style="width: 120px; float: left;" type="button" value="Create Order">
    <button id="hdclose" onclick="showStuff(document.getElementById('tabs1'));" style="width: 120px; float: right;" type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <br />

}

Mvc5MobileApplicationSG/Views/SpringGarden/paid.cshtml
@model Mvc5MobileApplicationSG.Models.MenuRetievalModel

@{
    ViewBag.Title = "paid";
}
<script>

    function refresh() {

        var url = '@Url.Action("mainPage", "SpringGarden")';

        window.location = url;

    }

</script>

<body>

   
    <h3>Your order has been successfully confirmed, pickups ready in 20 - 30 mins, deliveries ready within 1 hour</h3>

        <button id="paymentsuccessclose" onclick="refresh();" type="button" class="btn btn-default" data-dismiss="modal">Close</button>



</body>

Mvc5MobileApplicationSG/Views/SpringGarden/paiddelivery.cshtml
@model Mvc5MobileApplicationSG.Models.MenuRetievalModel

@{
    ViewBag.Title = "paid";
}
<script>

    function refresh() {

        var url = '@Url.Action("mainPage", "SpringGarden")';

        window.location = url;

    }

</script>

<body>

    <h3>Your Order has been successfully confirmed, deliveries will be delivered within at least 1 hour, pickups ready in at least 30 mins</h3>

   <button id="paymentsuccessclose" onclick="refresh();" type="button" class="btn btn-default" data-dismiss="modal">Close</button>

</body>

Mvc5MobileApplicationSG/Views/SpringGarden/paymentdialog.cshtml
@model Mvc5MobileApplicationSG.Models.MenuRetievalModel

@{
    ViewBag.Title = "paymentdialog";
}


<script src="https://js.stripe.com/v3/"></script>
<script>

    function paid(amount) {

        var url = '@Url.Action("payment", "SpringGarden")';

    $.ajax({
        url: url,
        type: "GET",
        data: { amount: amount },
        success: function (results) {
            return true;

        },
        error: function (jqXHR, textStatus, errorThrown) {
            alert(jqXHR.status);
            alert(textStatus);
            alert(errorThrown);
        },


    });
        return false;

    }


    function validateContact() {

         if ($("#emailpaymentid").val() == "") {
            alert("email field required");
            return false;
        }

        if ($("#cashcardid").val() == "") {
            alert("Please inform your payment type: cash or card?");
            return false;
        }


        
        hidden();

        var url = '@Url.Action("validateContact", "SpringGarden")';
        var email = String(document.getElementById("emailpaymentid").value);
        var cashcard = String(document.getElementById("cashcardid").value);
        $.ajax({
            url: url,
            type: "GET",
            data: { email: email, cashcard: cashcard },
            success: function (results) {

                $("#items").html(results);

            },
            error: function (jqXHR, textStatus, errorThrown) {
                alert(jqXHR.status);
                alert(textStatus);
                alert(errorThrown);
            },
        });

        return false;
    }


    function paymentclick(amount) {

        var clientSecret = "";

    hidden();
    var url = '@Url.Action("pay", "SpringGarden")';

    $.ajax({
        url: url,
        type: "GET",
        datatype: "JSON",
        contentType: "application/json;charset=utf-8",
        data: { amount: amount },
        success: function (results) {

             clientSecret = results.clientsecret;
           // alert(ClientSecret);
        stripe.confirmCardPayment(clientSecret, {
            payment_method: {
                card: card
            }
        }).then(function (result) {

            if (result.error) {
                // Show error to your customer (e.g., insufficient funds)
                showAll();
                alert("Declined Transaction, please try agagin");
                console.log(result.error.message);
            } else {

                // The payment has been processed!
                if (result.paymentIntent.status === 'succeeded') {
                    paid(amount);
                    alert("Succeeded payment\n\nYour Order has been successfully paid, deliveries will be delivered within the 1 hour, pickups ready in 30 mins");
                    var backButton = document.getElementById("paymentclosedialog");
                    backButton.click();
                    location.reload();
                    // Show a success message to your customer
                    // There's a risk of the customer closing the window before callback
                    // execution. Set up a webhook or plugin to listen for the
                    // payment_intent.succeeded event that handles any business critical
                    // post-payment actions.
                }
            }
        });


        },
        error: function (jqXHR, textStatus, errorThrown) {
            alert(jqXHR.status);
            alert(textStatus);
            alert(errorThrown);
        },

    });


        return false;


    }

    function hidden() {

        $.ajaxSetup({
            beforeSend: function () {
                // show gif here, eg:
                $("#processing").show();
                $('#confirmcontact').hide();
                $('#paymentclosedialog').hide();
            },
            complete: function () {
                // hide gif here, eg:
                 $("#processing").hide();
                $('#confirmcontact').show();
                $('#paymentclosedialog').show();
            }
        });
    }
        function showPaymentDialog() {

            $("#processing").hide();
            $('#confirmcontact').show();
            $('#paymentclosedialog').show();

        };

    


    $("#submitmodify").click(function () {
        if ($("#radiobutton").val() == "") {
            alert("selection field required");
            return false;
        }

        return true;


    });

    


    window.onload = function () {


        showAll();


        };



    function show() {

        $.ajax({
            success: function () {
                // do something

                var paymentclosebutton = document.getElementById("paymentclosedialog");
                paymentclosebutton.style.display = "block";

                var processingbar = document.getElementById("processing");
                processingbar.style.diplay = "none";


            }
        });
    }


    function showAll() {

        $('#submitpayment').show();
        $('#paymentclosedialog').show();
        $("#processing").hide();

    }
   
    // A reference to Stripe.js initialized with your real SpringGarden publishable API key.
    var stripe = Stripe('pk_live_yXxKTaVfdkgQQ3xyaCK8sXGp00D9nErvsC', {
  stripeAccount: "acct_1H04BzHkIdluiEg0"
    });

  //  var stripe = Stripe("pk_live_yXxKTaVfdkgQQ3xyaCK8sXGp00D9nErvsC");
 //   var stripe = Stripe("pk_SpringGarden_51GuFRFGSzY6XVzcspooKuyVIwxLpm8gUu6MILROJei6FrtEegl0XnI7H1mN2ydKenuyjfe2kOpK2wVVgHjLmKYwL00X9ed1Bax");

// The items the customer wants to buy

    var elements = stripe.elements();



var form = document.getElementById('payment-form');


  var style = {
  base: {
    color: "#32325d",
  }
};

var card = elements.create("card", { style: style });
card.mount("#card-element");


    card.on('change', ({error}) => {
  const displayError = document.getElementById('card-errors');
  if (error) {
    displayError.textContent = error.message;
  } else {
    displayError.textContent = '';
  }
    });



</script>

<hiddeninput id="clientsecret" value="@ViewData["ClientSecret"]" />
<form id="payment-form">
    <div id="total" style="left: initial; margin-left: 1%">

        @{
            double total = 0;
            var suburb = "";

            if (Model != null && Model.RecallItems != null)
            {
                <ul>
                    @for (int i = 0; i < Model.RecallItems.Count; i++)
                    {

                        if (Model.RecallItems[i].discountflag == null || Model.RecallItems[i].discountflag == "" || Model.RecallItems[i].discountflag == "N")
                        {

                            if (!@Model.RecallItems[i].isSpecial())
                            {
                                <li style="font-size: 10px">
                                    <button style="align-self:center; font-size: 10px; color: white; background: green;" onclick="return updateQty('add', '@Model.RecallItems[i].getinputboxstr()', '@Model.RecallItems[i].itemno')">+</button><input style="width: 30px; font-size: 10px; color: black;" type="button" value="@Model.RecallItems[i].itemqty" /><button style="align-self:center; font-size: 10px; color: white; background: green;" onclick="return updateQty('deduct', '@Model.RecallItems[i].getinputboxstr()', '@Model.RecallItems[i].itemno')">-</button> $@String.Format("{0:0.00}", @Math.Round(@Model.RecallItems[i].itemprice, 2)) @Model.RecallItems[i].itemname.Trim().ToUpper()


                                    @if (@Model.CurrentItemSelected(@Model.RecallItems[i].actualitemno).getNonForcedModifiers().Count() > 0 && @Model.RecallItems[i].itemqty == 1)
                                    {

                                        <button type="button" style="align-self:center; font-size: 10px; color: white; background: green;" onclick="return modify('@Model.RecallItems[i].itemno', '@Model.RecallItems[i].actualitemno')"> Modify </button>
                                        <hiddenbutton type="button" id="modifybutton" data-toggle="modal" data-target="#modifiermodal"></hiddenbutton>


                                    }

                                </li>

                            }
                            else
                            {
                                <li style="font-size: 10px">
                                    @Model.RecallItems[i].itemqty X $@String.Format("{0:0.00}", @Math.Round(@Model.RecallItems[i].itemprice, 2)) @Model.RecallItems[i].itemname.Trim().ToUpper()
                                </li>
                            }

                            <br />
                        }
                        else
                        {
                            suburb = @Model.RecallItems[i].itemname.Trim() + " at " + "$" + @String.Format("{0:0.00}", @Math.Round(@Model.RecallItems[i].itemprice, 2));

                        }



                        total = total + @Model.RecallItems[i].itemqty * @Model.RecallItems[i].itemprice;
                    }
                </ul>
                <p>---------------------------------------------</p>
                <h5>@suburb</h5>

                <h2>Sub Total: $@String.Format("{0:0.00}", @Math.Round(total, 2))</h2>
                <p>---------------------------------------------</p>
            }
            else
            {
                <h3>No Items Selected Yet</h3>
            }

        }

        @if ((total >= 30 && Model.OrderType == "homedelivery") || Model.OrderType == "takeaway")
        {
            <!--   <h5>Please enter credit card details below:</h5> -->
            <!--    <div id="card-element">

        </div>
        -->
            <!-- We'll put the error messages in this element -->
            <!--    <div id="card-errors" role="alert"></div> -->
            <!--
        <br />
        <br />
        <div id="processing" style="display: none"><h5>processing please wait...</h5></div>
        <button id="submitpayment" data-secret="@ViewData["ClientSecret"]" style="width: 100px; float: left;" class="btn btn-default" type="submit" onclick="return paymentclick('@String.Format("{0:0.00}", @Math.Round(total, 2))');">Pay Card</button>
        <button id="paymentclosedialog" style="width: 100px; float: right;" type="button" class="btn btn-default" data-dismiss="modal">Back</button>

        -->
            <h3>Please ensure your email phone contact details are correct and confirm purchase, a pin will be sent to your email</h3>
            <label>Email:</label>
            <input id="emailpaymentid" type="text" value="@Model.email" style="width: 300px;" />
            <h5>*please ammend your email if its incorrect, by clicking in the text box above</h5>
            <br />
            <label for="name">Cash or Card payment? (mandatory*):</label>
            <label for="cashcard">Choose a payment:</label>

            <select name="cashcard" id="cashcardid">
                <option value=""></option>
                <option value="cash">cash</option>
                <option value="card">card</option>
            </select>

            <br />
            <br />

            <div id="processing" style="display: none"><h5>processing please wait...</h5></div>


            <button id="confirmcontact" style="width: 120px; float: left;" class="btn btn-default" type="button" onclick="return validateContact()">Confirm Order</button>
            <button id="paymentclosedialog" style="width: 100px; float: right;" type="button" class="btn btn-default" data-dismiss="modal">Back</button>

        }
        else
        {

            <h3>Home delivery orders must be minimum $50</h3>
            <button id="paymentclosedialog" type="button" class="btn btn-default" data-dismiss="modal">Back</button>


        }

        <br />


    </div>

</form>

Mvc5MobileApplicationSG/Views/SpringGarden/takeawaydialog.cshtml
@model Mvc5MobileApplicationSG.Models.MenuRetievalModel

@{
    ViewBag.Title = "paid";
}

<script>

     function createOrderTA() {


            var url = '@Url.Action("createOrderNonModelTA", "SpringGarden")';
            var name = document.getElementById("tanameid").value;
            var phone = document.getElementById("taphoneid").value;


         if (String(name) == "") {
             alert("Name required");
             return;


         }

         if (String(phone) == "") {
             alert("Phone required");
             return;


         }

            $.ajax({
                url: url,
                type: "POST",
                data: { name: name, phone: phone },
                success: function (results) {
                    $("#tabs-1").html(results);
                    OnSuccess();
                    var closebutton = document.getElementById("taclose");
                    closebutton.click();
                },


            });

            return false;
    }




</script>

@if (Model.email == null || Model.email.Trim() == "")
{

    <h1>Cannot find details</h1>
    <div class="w3-container" id="deliverycontent">
        <h4 class="modal-title">Take away</h4>

        <p>Please enter details</p>
        <label for="name">Name:</label>
        <input id="tanameid" class="w3-input" type="text" value="">

        <br />
        <label for="name">Phone:</label>
        <input id="taphoneid" class="w3-input" type="text" value="">
        <br />
        <input id="submitta" onclick="createOrderTA();" style="width: 120px; float: left;" type="button" value="Create Order" />
        <button onclick="showStuff(document.getElementById('tabs1'));" id="taclose" style="width: 120px; float: right;" type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <br />
    </div>

   
}
else
{

<div class="w3-container" id="deliverycontent">
    <h4 class="modal-title">Take away</h4>

    <p>Please enter details</p>
    <label for="name">Name:</label>
    <input id="tanameid" class="w3-input" type="text" value="@Model.name">

    <br />
    <label for="name">Phone:</label>
    <input id="taphoneid" class="w3-input" type="text" value="@Model.phone">
    <br />

    <input id="submitta" onclick="createOrderTA();" style="width: 120px; float: left;" type="button" value="Create Order" />
    <button onclick="showStuff(document.getElementById('tabs1'));" id="taclose" style="width: 120px; float: right;" type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <br />
</div>


}