Mvc5MobileApplicationSG/Controllers/ChomolungmaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mvc5MobileApplicationSG.Models;
using Stripe;

namespace Mvc5MobileApplicationSG.Controllers
{
    public class ChomolungmaController : Controller
    {

        public static string ABN = "86602312069";


        public ActionResult About()
        {
            ViewBag.Message = "Your app description page.";

            return PartialView("About");
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return PartialView("Contact");
        }

        public ActionResult mainPage()
        {
            return View("Unavailable");

            MenuRetievalModel model = new MenuRetievalModel();
            model.ABN = ABN;
            model.alertmessage = "";
            Session["model"] = model;
            ViewBag.ErrorMessage = "";
            model.getCategories();
            return View("mainPage", model);


        }

        public ActionResult mainPageSession()
        {
            MenuRetievalModel model = (MenuRetievalModel)Session["model"];
            model.getCategories();
            return View("mainPage", model);
        }

        public ActionResult getDeliveryItem()
        {


            MenuRetievalModel model = (MenuRetievalModel)Session["model"];

            if (!model.getDeliveryOn())
            {
                return View("deliveryOffline");
            }

            model.getCategories();
            return PartialView("getMenuOrder", model);



        }

        [HttpGet]
        public ActionResult validateContact(String email, String cashcard)
        {


            ((MenuRetievalModel)Session["model"]).email = email;
            ((MenuRetievalModel)Session["model"]).Notes = cashcard;

            Session["id"] = ((MenuRetievalModel)Session["model"]).generateID();
            ((MenuRetievalModel)Session["model"]).updateContact();

            ViewBag.Invalid = "";

            return PartialView("validateContact", (MenuRetievalModel)Session["model"]);


        }

        [HttpGet]
        public ActionResult validateContactBooking(MenuRetievalModel model)
        {

            ((MenuRetievalModel)Session["model"]).BookingTable = model.BookingTable;
            ((MenuRetievalModel)Session["model"]).email = model.email;
            ((MenuRetievalModel)Session["model"]).OrderType = "booking";
            createBooking((MenuRetievalModel)Session["model"]);
            Session["id"] = ((MenuRetievalModel)Session["model"]).generateID();
            ((MenuRetievalModel)Session["model"]).updateContact();


            ViewBag.Invalid = "";
            ((MenuRetievalModel)Session["model"]).ProgressToBookingConfirmation = true;
            return PartialView("validateContact", (MenuRetievalModel)Session["model"]);


        }

        [HttpGet]
        public ActionResult validateBooking(String id)
        {

            if (id == Session["id"].ToString())
            {

                ((MenuRetievalModel)Session["model"]).confirmedcontact();
                return PartialView("confirmedbooking", (MenuRetievalModel)Session["model"]);


            }
            else
            {
                ViewBag.Invalid = "Invalid Pin, Please try again";
                return PartialView("validateContact", (MenuRetievalModel)Session["model"]);


            }



        }

        [HttpGet]
        public ActionResult validateDetails(String id, String ordertype)
        {

            if (id == Session["id"].ToString())
            {
                if (ordertype == "homedelivery")
                {
                    return PartialView("delivery", (MenuRetievalModel)Session["model"]);

                }
                else if (ordertype == "takeaway")
                {

                    return PartialView("takeawaydialog", (MenuRetievalModel)Session["model"]);

                }
                else
                {

                    return PartialView("bookingdialog", (MenuRetievalModel)Session["model"]);

                }
            }
            else
            {
                ViewBag.Invalid = "Invalid Pin, Please try again";
                return PartialView("validateContact", (MenuRetievalModel)Session["model"]);


            }



        }



        [HttpGet]
        public ActionResult validate(String id)
        {

            if (id == Session["id"].ToString())
            {
                ((MenuRetievalModel)Session["model"]).confirmedcontact();
                return PartialView("paid", (MenuRetievalModel)Session["model"]);


            }
            else
            {
                ViewBag.Invalid = "Invalid Pin, Please try again";
                return PartialView("validateContact", (MenuRetievalModel)Session["model"]);


            }



        }


        [HttpGet]
        public ActionResult findContactBooking(String phone)
        {
            if (Session["model"] == null)
            {
                refreshsession();

            }

            ((MenuRetievalModel)Session["model"]).OrderType = "booking";

            ((MenuRetievalModel)Session["model"]).bookingrequest = true;

            ((MenuRetievalModel)Session["model"]).phonesearch = phone;

            ((MenuRetievalModel)Session["model"]).findcontactBooking(phone);

            if (((MenuRetievalModel)Session["model"]).email != null && ((MenuRetievalModel)Session["model"]).email.Trim() != "")
            {
                Session["id"] = ((MenuRetievalModel)Session["model"]).generateID();


                return PartialView("validateContact", (MenuRetievalModel)Session["model"]);

            }

            return PartialView("bookingdialog", ((MenuRetievalModel)Session["model"]));


        }

        [HttpGet]
        public ActionResult findContactTA(String phone)
        {
            if (Session["model"] == null)
            {
                refreshsession();

            }

            ((MenuRetievalModel)Session["model"]).OrderType = "takeaway";

            ((MenuRetievalModel)Session["model"]).phonesearch = phone;

            ((MenuRetievalModel)Session["model"]).findcontactTA(phone, "takeaway");

            if (((MenuRetievalModel)Session["model"]).email != null && ((MenuRetievalModel)Session["model"]).email.Trim() != "")
            {
                Session["id"] = ((MenuRetievalModel)Session["model"]).generateID();


                return PartialView("validateContact", (MenuRetievalModel)Session["model"]);

            }

            return PartialView("takeawaydialog", ((MenuRetievalModel)Session["model"]));


        }


        [HttpGet]
        public ActionResult findContactDelivery(String phone)
        {
            if (Session["model"] == null)
            {
                refreshsession();

            }

            ((MenuRetievalModel)Session["model"]).OrderType = "homedelivery";

            ((MenuRetievalModel)Session["model"]).phonesearch = phone;

            ((MenuRetievalModel)Session["model"]).findcontact(phone, "homedelivery");

            if (((MenuRetievalModel)Session["model"]).email != null && ((MenuRetievalModel)Session["model"]).email.Trim() != "")
            {
                Session["id"] = ((MenuRetievalModel)Session["model"]).generateID();


                return PartialView("validateContact", (MenuRetievalModel)Session["model"]);

            }

            return PartialView("delivery", ((MenuRetievalModel)Session["model"]));


        }


        public ActionResult getMenuCatItem()
        {

            if (Session["model"] == null)
            {
                refreshsession();

            }
            MenuRetievalModel model = (MenuRetievalModel)Session["model"];

            return PartialView("getMenuOrder", (MenuRetievalModel)Session["model"]);

        }


        [HttpGet]
        public ActionResult getSearchDialog(String ordertype)
        {
            if (Session["model"] == null)
            {
                refreshsession();

            }


            ((MenuRetievalModel)Session["model"]).OrderType = ordertype;

            return PartialView("search", (MenuRetievalModel)Session["model"]);


        }


        [HttpGet]
        public ActionResult getSearchDialogBooking()
        {
            if (Session["model"] == null)
            {
                refreshsession();

            }


            ((MenuRetievalModel)Session["model"]).OrderType = "booking";

            return PartialView("search", (MenuRetievalModel)Session["model"]);


        }



        [HttpGet]
        public ActionResult getBookingDialog()
        {
            if (Session["model"] == null)
            {
                refreshsession();

            }

            ((MenuRetievalModel)Session["model"]).ProgressToBookingTable = false;
            ((MenuRetievalModel)Session["model"]).ProgressToBookingConfirmation = false;
            return PartialView("bookingdialog", (MenuRetievalModel)Session["model"]);


        }

        [HttpGet]
        public ActionResult getDeliveryDialog()
        {
            if (Session["model"] == null)
            {
                refreshsession();

            }

            ((MenuRetievalModel)Session["model"]).confirmDetails = false;
            ((MenuRetievalModel)Session["model"]).noDetails = true;
            ((MenuRetievalModel)Session["model"]).ProgressToBookingConfirmation = false;
            return PartialView("delivery", (MenuRetievalModel)Session["model"]);


        }

        public void refreshsession()
        {

            Session["model"] = new MenuRetievalModel();
            ((MenuRetievalModel)Session["model"]).ABN = ABN;
            ((MenuRetievalModel)Session["model"]).getCategories();

        }


        [HttpPost]

Mvc5MobileApplicationSG/Views/Chomolungma/Unavailable.cshtml
This site is no longer available please call restaurant directly

Mvc5MobileApplicationSG/Views/Chomolungma/ViewShoppingCart.cshtml
@model Mvc5MobileApplicationSG.Models.MenuRetievalModel


<button onclick="recallbill('@Model.name');">Shopping Cart</button>
<hiddenbutton id="paymentbutton" style="display: none;" data-toggle="modal" data-target="#paymentsummarymodal" onclick="'@Model.recallDetails()'" />

Mvc5MobileApplicationSG/Views/Chomolungma/bookingtable.cshtml
@model Mvc5MobileApplicationSG.Models.MenuRetievalModel

@{
    ViewBag.Title = "bookingdialog";
}


<script>



    function validateemail() {

        if ($("#bookingemailid").val() == "") {
            alert("email field required");
            return false;
        }

        hiddenBooking();

        return true;

    }

    function backBookingDialog() {



            var url = '@Url.Action("getBookingDialog", "Chomolungma")';

            $.ajax({
                url: url,
                type: "GET",
                data: { },
                success: function (results) {
                    $("#bookingitems").html(results);
                    bookingFunction();

                },


            });

            return false;
    }




</script>


<div id="processingbooking" style="display: none"><h5>processing please wait...</h5></div>
<br />
@using (Ajax.BeginForm("validateContactBooking", "Chomolungma", null, new AjaxOptions { HttpMethod = "Get", UpdateTargetId = "bookingitems", OnBegin = "hiddenBooking()", OnComplete = "showAllBooking()" }, null))
{

    if (@Model.TablesItems != null && @Model.TablesItems.Count() > 0)
    {
        <div style="float:left; left: 0px;">
            <label for="name" style="width: 200px; float: left;">Table selection (mandatory*):</label>
            <br />
            <br />
            @Html.DropDownListFor(m => m.BookingTable, Model.TablesItems, new { @id = "tablebookingid", @style = "width:250px;float:left;" })
            <br />
            <br />
            <label for="name" style="width: 200px; float: left;">email: (mandatory*):</label>
            <br />
            <br />
            @Html.TextBoxFor(m => m.email, new { @id = "bookingemailid", @style = "width:200px;float:left;" })
            <br />
            <br />
            <br />
            <br />
            <input id="submitbooking" onclick="return validateemail();" type="submit" value="create booking" style="width: 150px; float: left;" />
            <input id="backbooking" onclick="return backBookingDialog();" type="button" value="Back" style="width: 150px; float: left;" data-dismiss="modal" />
        </div>



    }


}

Mvc5MobileApplicationSG/Views/Chomolungma/delivery.cshtml
@model Mvc5MobileApplicationSG.Models.MenuRetievalModel

@{
    ViewBag.Title = "delivery";
}

<script>

     function createOrder() {


            var url = '@Url.Action("createOrderNonModel", "Chomolungma")';
            var name = document.getElementById("nameid").value;
            var phone = document.getElementById("phoneid").value;
            var address = document.getElementById("addressid").value;
         var suburb = document.getElementById("suburbid").value;

         if (String(name) == "") {
             alert("Name required");
             return;


         }

         if (String(phone) == "") {
             alert("Phone required");
             return;


         }

         if (String(address) == "") {
             alert("Address required");
             return;


         }

         if (String(suburb) == "") {
             alert("Suburb required");
             return;


         }


            $.ajax({
                url: url,
                type: "POST",
                data: { name: name, phone: phone, address: address, itemno: suburb },
                success: function (results) {
                    $("#tabs-1").html(results);
                    OnSuccess();
                    var closebutton = document.getElementById("hdclose");
                    closebutton.click();
                },


            });

            return false;
    }




</script>

@if (Model.email == null || Model.email.Trim() == "")
{
    <center><h4 class="modal-title" style="font-weight: bold;">Delivery</h4></center>

    <div class="w3-container" id="deliverycontent">
        <h4 style="color: red;font-weight: bold;">Cannot find details</h4>

        <h4>*Please enter details</h4>

        <form style="display: table">
            <div style="display: table-row">
                <label style="display: table-cell;padding-right: 2vw;" for="name">*Name:</label>
                <input style="display: table-cell" id="nameid" class="w3-input" type="text" value="">
            </div>
            <br />
            <div style="display: table-row">
                <label style="display: table-cell;padding-right: 2vw;" for="name">*Phone:</label>
                <input style="display: table-cell" id="phoneid" class="w3-input" type="text" value="">

            </div>
            <br />
            <div style="display: table-row">
                <label style="display: table-cell;padding-right: 2vw;" for="name">*Address:</label>
                <input style="display: table-cell" id="addressid" class="w3-input" type="text" value="">
            </div>
            <br />
            <div style="display: table-row">
                <label for="name" style="display: table-cell;padding-right: 3vw;">*Suburb:</label>
                @if (@Model.TransferItems != null)
                {
                    @Html.DropDownListFor(m => m.itemno, Model.TransferItems, new { @id = "suburbid", style = "width: 200px; height: 30px; display: table-cell;" })

                }

            </div>
        </form>


        <br />
    </div>
    <br />
    <br />
    <input id="submithd" onclick="createOrder();" style="width: 120px; float: left; font-weight: bold;" type="button" value="Create Order">
    <button id="hdclose" onclick="showStuff(document.getElementById('tabs1'));" style="width: 120px; float: right; font-weight: bold;" type="button" data-dismiss="modal">Close</button>
    <br />
}
else
{

<div class="w3-container" id="deliverycontent">
    <center><h4 class="modal-title" style="font-weight: bold;">Delivery</h4></center>
    <h4>*Please enter details</h4>

    <form style="display: table">
        <div style="display: table-row">
            <label style="display: table-cell" for="name">*Name:</label>
            <input style="display: table-cell" id="nameid" class="w3-input" type="text" value="@Model.name">
        </div>
        <br />
        <div style="display: table-row">
            <label style="display: table-cell" for="name">*Phone:</label>
            <input style="display: table-cell" id="phoneid" class="w3-input" type="text" value="@Model.phone">

        </div>
        <br />
        <div style="display: table-row">
            <label style="display: table-cell" for="name">*Address:</label>
            <input style="display: table-cell" id="addressid" class="w3-input" type="text" value="@Model.address">
        </div>
        <br />

    </form>
    <label for="name">*Suburb:</label>
    @if (@Model.TransferItems != null)
    {
        @Html.DropDownListFor(m => m.itemno, Model.TransferItems, new { @id = "suburbid", style = "width: 200px; height: 30px" })

    }
    <br />
</div>
    <br />
    <br />
    <input id="submithd" onclick="createOrder();" style="width: 120px; float: left; font-weight: bold;" type="button" value="Create Order">
    <button id="hdclose" onclick="showStuff(document.getElementById('tabs1'));" style="width: 120px; float: right; font-weight: bold;" type="button" data-dismiss="modal">Close</button>
    <br />

}

Mvc5MobileApplicationSG/Views/Chomolungma/deliveryOffline.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>

    <script>

    function home() {
        // Now add markers
        var url = '@Url.Action("mainPage", "Chomolungma")'
        window.location = url;

    }

    </script>

</head>
<body>
    <div>
        <h1>Online Delivery is currently offline, please try again later on opening hours (see Contact page for details) 
            or call (02) 6296 3111 to make your order</h1>

        <button style="font-size: 15px;" onclick="home();">Back</button>



    </div>
</body>
</html>

Mvc5MobileApplicationSG/Views/Chomolungma/expiredSession.cshtml
@{
    ViewBag.Title = "expiredSession";
}

<script>

    function home() {
        // Now add markers
        var url = '@Url.Action("mainPage", "Chomolungma")'
        window.location = url;
        
    }

</script>

<body style="background-color: green;">

    <h1>Your session at Chomolungma Website has expired.</h1>

    <button style="font-size: 15px;" onclick="home();">Chomolungma Home Page</button>

</body>

Mvc5MobileApplicationSG/Views/Chomolungma/forceModify.cshtml
@model Mvc5MobileApplicationSG.Models.MenuRetievalModel


<div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
        <div class="modal-header">
        </div>
        <div class="modal-body">
            @if (!Model.getDeliveryOn() && !Model.Debug)
            {
                <h1>Cloud Service Currently Offline please try again later. Please refresh your internet browser when trying again by closing and reopening this page.</h1>

                <button id="hdclose" type="button" class="btn btn-default" data-dismiss="modal">Close</button>

            }
            else
            {
                using (Ajax.BeginForm("forceModify", "Chomolungma", null, new AjaxOptions { HttpMethod = "Post", UpdateTargetId = "items", OnSuccess = "OnSuccessModify" }, null))
                {

        <div id="deliverycontent">
            <h4 style="font-weight: bold;">Customise</h4>
            <br />

           
                @for (int i = 0; i < Model.CurrentItemSelected().Modifiermodels.Count; i++)
                {

                    if (@Model.CurrentItemSelected().Modifiermodels[i].forced == "Y")
                    {
                        if (i == 0)
                        {
                            <label for="name" style="padding-left: 15px;">@Model.CurrentItemSelected().Modifiermodels[i].BtnDesc</label>
                            @Html.RadioButtonFor(m => m.modBtnDesc, @Model.CurrentItemSelected().Modifiermodels[i].BtnDesc, new { @id = "radiobutton", style = "font-size: 15px; padding-right: 15px;", @checked = "true" })
                            @Html.HiddenFor(m => m.modPrice, @Model.CurrentItemSelected().Modifiermodels[i].price)

                        }
                        else
                        {
                            <label for="name" style="padding-left: 15px;">@Model.CurrentItemSelected().Modifiermodels[i].BtnDesc</label>
                            @Html.RadioButtonFor(m => m.modBtnDesc, @Model.CurrentItemSelected().Modifiermodels[i].BtnDesc, new { @id = "radiobutton", style = "font-size: 15px; padding-right: 15px;" })
                            @Html.HiddenFor(m => m.modPrice, @Model.CurrentItemSelected().Modifiermodels[i].price)
                        }
                    }


                }

          
        </div>
                    <br />
                    <input id="submitmodify" type="submit" value="Done" data-toggle="modal" data-target="#forcedmodifiermodal" />

                    <br />


                }

            }
        </div>
    </div>



</div>

Mvc5MobileApplicationSG/Views/Chomolungma/modify.cshtml
@model Mvc5MobileApplicationSG.Models.MenuRetievalModel

<script>


    function paymentDialog() {


            var url = '@Url.Action("back", "Chomolungma")';

            $.ajax({
                url: url,
                type: "GET",
                data: { },
                success: function (results) {
                    $("#items").html(results);
                    bookingFunction();

                },


            });

            return false;
    }



</script>

@if (!Model.getDeliveryOn() && !Model.Debug)
{
    <h1>Cloud Service Currently Offline please try again later. Please refresh your internet browser when trying again by closing and reopening this page.</h1>

    <button type="button" data-toggle="modal" data-target="#modifiermodal"> Close </button>

}
else
{
    using (Ajax.BeginForm("modify", "Chomolungma", null, new AjaxOptions { HttpMethod = "Post", UpdateTargetId = "items", OnSuccess = "modifysuccess" }, null))
    {
      
        <br />
        <div id="deliverycontent">

            @if (@Model.CurrentItemSelected() != null)
            {
                @Html.DropDownListFor(m => m.modBtnDesc, @Model.CurrentItemSelected().getNonForcedModifiers(), new { @id = "modcode", @style = "width: 300px; height: 30px;" })
                @Html.HiddenFor(m => m.itemno, @Model.itemno)
                @Html.HiddenFor(m => m.actualitemno, @Model.actualitemno)

            }

        </div>
        <br />
        <br />
        <button id="submitmodifyitem" type="submit" style="float: left; width: 100px;" data-toggle="modal" data-target="#paymentsummarymodal"> Add </button>
        <button type="button" onclick="paymentDialog();" style="float: right; width: 100px;" > Close </button>
        <br />


    }

}

Mvc5MobileApplicationSG/Views/Chomolungma/paid.cshtml
@model Mvc5MobileApplicationSG.Models.MenuRetievalModel

@{
    ViewBag.Title = "paid";
}
<script>

    function refresh() {

        var url = '@Url.Action("mainPage", "Chomolungma")';

        window.location = url;

    }

</script>

<body>

   
    <h3>Your order has been successfully confirmed, pickups ready in 20 - 30 mins, deliveries ready within 1 hour</h3>

        <button id="paymentsuccessclose" onclick="refresh();" type="button" class="btn btn-default" data-dismiss="modal">Close</button>



</body>

Mvc5MobileApplicationSG/Views/Chomolungma/search.cshtml
@model Mvc5MobileApplicationSG.Models.MenuRetievalModel

@{
    ViewBag.Title = "search";
}

<script>



    function findContactTA() {

        if ($("#findcontactphoneid").val() == "" && $("#findcontactphonetakeawayid").val() == "") {
            alert("phone field required");
            return false;
        }

        hiddenSearchTA();

        url = '@Url.Action("findContactTA", "Chomolungma")';


        var phone = document.getElementById("findcontactphonetakeawayid").value;

        $.ajax({
            url: url,
            type: "GET",
            cache: true,
            data: { phone: phone },
            success: function (results) {
                $('head').append('<link rel="stylesheet" type="text/css" href="style.css">');
                $("#takeawayid").html(results);

                return false;
            },
            error: function (jqXHR, textStatus, errorThrown) {
                alert(jqXHR.status);
                alert(textStatus);
                alert(errorThrown);
            },

        });

    }


    function findContact() {

        if ($("#findcontactphoneid").val() == "" && $("#findcontactphonetakeawayid").val() == "") {
            alert("phone field required2");
            return false;
        }

        hiddenSearch();

        url = '@Url.Action("findContactDelivery", "Chomolungma")';


        var phone = document.getElementById("findcontactphoneid").value;

        $.ajax({
            url: url,
            type: "GET",
            cache: true,
            data: { phone: phone },
            success: function (results) {
                $('head').append('<link rel="stylesheet" type="text/css" href="style.css">');
                $("#deliveryid").html(results);

                return false;
            },
            error: function (jqXHR, textStatus, errorThrown) {
                alert(jqXHR.status);
                alert(textStatus);
                alert(errorThrown);
            },

        });

    }

    function findContactBooking() {

        if ($("#findcontactphoneid").val() == "" && $("#findcontactphonebookingid").val() == "") {
            alert("phone field required");
            return false;
        }

        hiddenSearchBooking();

        url = '@Url.Action("findContactBooking", "Chomolungma")';


        var phone = document.getElementById("findcontactphonebookingid").value;

        $.ajax({
            url: url,
            type: "GET",
            cache: true,
            data: { phone: phone },
            success: function (results) {
                $('head').append('<link rel="stylesheet" type="text/css" href="style.css">');
                $("#bookingitems").html(results);

                return false;
            },
            error: function (jqXHR, textStatus, errorThrown) {
                alert(jqXHR.status);
                alert(textStatus);
                alert(errorThrown);
            },

        });

    }


    function hiddenSearchBooking() {


        $('#submitfindbookingcontact').hide();
        document.getElementById("searchprogressid").style.display = "block";
        $("#bookingsearchclose").hide();


    }


    function hiddenSearch() {


        $('#submitfindhdcontact').hide();
        document.getElementById("searchprogressid").style.display = "block";
        $("#hdsearchclose").hide();


    }


    function hiddenSearchTA() {


        $('#submitfindtacontact').hide();
   //     $('#searchprogressid').show();
        $("#tasearchclose").hide();


    }





</script>

@if (!Model.confirmDetails)
{



    if (Model.OrderType == "homedelivery")
    {
        <div class="w3-container" id="deliverycontent">
            <center><h4 class="modal-title" style="font-weight: bold;">Delivery</h4></center>

            <p>Please enter phone:</p>

            <input id="findcontactphoneid" class="w3-input" type="text" value="">
            <br />
            <p>*Please enter contact number and click <bold>Search</bold></p>

        </div>
        <br />
     <!--   <div id="searchprogressid" style="display: none;">
            <h4>*Please wait to find your contact details, this may take a few seconds to process...</h4>
        </div> -->
        <br />
        <button id="submitfindhdcontact" onclick="findContact();" style="width: 120px; float: left; font-weight: bold;" type="button">Search</button>
        <button id="hdsearchclose" onclick="showStuff(document.getElementById('tabs1'));" type="button" style="width: 120px; float: right; font-weight: bold;" data-toggle="modal" data-target="#deliverymodal">Close</button>
        <br />

    }
    else if (Model.OrderType == "takeaway")
    {
        <div class="w3-container" id="takeawaycontent">
            <center><h4 class="modal-title" style="font-weight: bold;">Take away</h4></center>

            <p>Please enter phone:</p>

            <input id="findcontactphonetakeawayid" class="w3-input" type="text" value="">
            <br />
            <p>*Please enter contact number and click <bold>Search</bold></p>

        </div>

        <!--  <div id="searchprogressid" style="display: none">
                    <h4>*Please wait to find your contact details, this may take a few seconds to process...</h4>
                </div> -->
                <br />
                <button id="submitfindtacontact" onclick="findContactTA();" style="width: 120px; float: left; font-weight: bold;" type="button">Search</button>
                <button id="tasearchclose" onclick="showStuff(document.getElementById('tabs1'));" type="button" style="width: 120px; float: right; font-weight: bold;" data-toggle="modal" data-target="#takeawaymodal">Close</button>
                <br />

            }
            else if (Model.OrderType == "booking")
            {
                <div class="w3-container" id="bookingcontent">
                    <center><h4 class="modal-title">Booking:</h4></center>

                    <p>Please enter details</p>
                    <h4>*Please enter contact number and click find, finding your contact details may take a few seconds to process...</h4>

                    <label for="name">Phone:</label>
                    <input id="findcontactphonebookingid" class="w3-input" type="text" value="">


                </div>
                <br />

                <div id="searchprogressid" style="display: none">
                    <h4>*Please wait to find your contact details, this may take a few seconds to process...</h4>
                </div>
                <br />
                <button id="submitfindbookingcontact" onclick="findContactBooking();" style="width: 120px; float: left;" type="button">Find</button>
                <button id="bookingsearchclose" onclick="showStuff(document.getElementById('tabs1'));" type="button" style="width: 120px; float: right;" data-toggle="modal" data-target="#bookingmodal">Close</button>
                <br />

            }

        }