Mvc5MobileApplicationSG/Controllers/POSAppController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mvc5MobileApplicationSG.Models;
using Stripe;


namespace Mvc5MobileApplicationSG.Controllers
{
    public class POSAppController : Controller
    {

        public static string ABN = "TESTDB";


        public ActionResult About()
        {
            ViewBag.Message = "Your app description page.";

            return PartialView("About");
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return PartialView("Contact");
        }

        public ActionResult mainPage()
        {

            MenuRetievalModel model = new MenuRetievalModel();
            model.ABN = ABN;
            model.alertmessage = "";
            Session["model"] = model;
            ViewBag.ErrorMessage = "";
            model.getCategories();
            return View("mainPage", model);


        }

        public ActionResult mainPageSession()
        {
            MenuRetievalModel model = (MenuRetievalModel)Session["model"];
            model.getCategories();
            return View("mainPage", model);
        }

        public ActionResult getDeliveryItem()
        {


            MenuRetievalModel model = (MenuRetievalModel)Session["model"];

            if (!model.getDeliveryOn())
            {
                return View("deliveryOffline");
            }

            model.getCategories();
            return PartialView("getMenuOrder", model);



        }



        public ActionResult getMenuCatItem()
        {

            MenuRetievalModel model = (MenuRetievalModel)Session["model"];

            return PartialView("getMenuOrder", (MenuRetievalModel)Session["model"]);

        }


        [HttpPost]
        public ActionResult createOrder(MenuRetievalModel model)
        {

            ((MenuRetievalModel)Session["model"]).name = model.name;
            ((MenuRetievalModel)Session["model"]).phone = model.phone;
            ((MenuRetievalModel)Session["model"]).address = model.address;
            ((MenuRetievalModel)Session["model"]).itemno = model.itemno; //suburb


            Session["orderdate"] = ((MenuRetievalModel)Session["model"]).createOrder("homedelivery");

            return PartialView("getMenuOrder", (MenuRetievalModel)Session["model"]);
        }

        [HttpPost]
        public ActionResult createTakeAway(MenuRetievalModel model)
        {


            ((MenuRetievalModel)Session["model"]).name = model.name;
            ((MenuRetievalModel)Session["model"]).phone = model.phone;

            Session["orderdate"] = ((MenuRetievalModel)Session["model"]).createOrderTA("takeaway");


            return PartialView("getMenuOrder", (MenuRetievalModel)Session["model"]);
        }


        public ActionResult updateQty(String itemno, String func)
        {

            ItemModel found = new ItemModel();
            MenuRetievalModel model = (MenuRetievalModel)Session["model"];


            found.itemno = itemno;
            int signal = 0;
            if (func == "add")
            {

                signal = 1;

            }
            else if (func == "deduct")
            {

                signal = -1;

            }
            model.transferItems(found, signal);

            model.recallDetails();



            return PartialView("paymentdialog", model);


        }

        public ActionResult refreshModel()
        {
            if (Session["model"] != null)
            {
                MenuRetievalModel model = (MenuRetievalModel)Session["model"];
                model.recallDetails();

            }

            return getMenuCatItem();
        }

        public void updateItemCode(String itemcode)
        {

            if (Session["model"] != null)
            {

                MenuRetievalModel model = (MenuRetievalModel)Session["model"];

                model.itemno = itemcode;


            }


        }


        [HttpGet]
        public JsonResult pay(String amount)
        {
            //CreateTransactionResponse response = new CreateTransactionResponse();
            //response.Transaction.OriginalTransactionId

            MenuRetievalModel model = (MenuRetievalModel)Session["model"];

            int amt = Convert.ToInt32((Convert.ToDouble(amount) * 100));
            PaymentIntent res = model.payIntent(amt);

            ViewData["ClientSecret"] = res.ClientSecret;

            return Json(new { clientsecret = res.ClientSecret }, JsonRequestBehavior.AllowGet);


        }

        [HttpGet]
        public ActionResult payment(String amount)
        {
            MenuRetievalModel model = (MenuRetievalModel)Session["model"];

            model.ABN = ABN;

            model.orderdate = (DateTime)Session["orderdate"];
            model.pay(amount);

            return PartialView("paymentdialog", model);


        }






        public ActionResult approved()
        {
            if (((MenuRetievalModel)Session["model"]).OrderType == "takeaway")
            {
                return PartialView("paid");
            }
            else
            {
                return PartialView("paiddelivery");

            }
        }

        public ActionResult declined()
        {

            return PartialView("declined");
        }

        public ActionResult expired()
        {

            return PartialView("expiredSession");

        }

        public ActionResult getShoppingCart()
        {

            return PartialView("ViewShoppingCart", (MenuRetievalModel)Session["model"]);

        }

        [HttpPost]
        public ActionResult forceModify(MenuRetievalModel model)
        {

            model.name = ((MenuRetievalModel)Session["model"]).name;
            model.phone = ((MenuRetievalModel)Session["model"]).phone;
            model.address = ((MenuRetievalModel)Session["model"]).address;
            model.itemno = ((MenuRetievalModel)Session["model"]).itemno; //suburb
            model.actualitemno = ((MenuRetievalModel)Session["model"]).itemno; //suburb
            model.Categories = ((MenuRetievalModel)Session["model"]).Categories;
            model.orderdate = (DateTime)Session["orderdate"];
            model.OrderType = ((MenuRetievalModel)Session["model"]).OrderType;
            model.ABN = ((MenuRetievalModel)Session["model"]).ABN;
            model.DataSetModifiers = ((MenuRetievalModel)Session["model"]).DataSetModifiers;
            Session["model"] = model;
            ModifierModel modon = model.GetNameOfModifierOn();
            model.forceModify(modon.BtnDesc, Convert.ToDecimal(modon.price));

            model.recallDetails();

            return PartialView("paymentdialog", (MenuRetievalModel)Session["model"]);
        }

        [HttpGet]
        public ActionResult getForceModfier(String itemno)
        {
            ((MenuRetievalModel)Session["model"]).itemno = itemno;
            ((MenuRetievalModel)Session["model"]).actualitemno = itemno;
            return PartialView("forceModify", (MenuRetievalModel)Session["model"]);

        }

        [HttpGet]
        public ActionResult getModifiers(String itemno, String actualitemno)
        {
            ((MenuRetievalModel)Session["model"]).itemno = itemno;
            ((MenuRetievalModel)Session["model"]).actualitemno = actualitemno;
            return PartialView("modify", (MenuRetievalModel)Session["model"]);

        }

        [HttpPost]
        public ActionResult modify(MenuRetievalModel model)
        {

            model.name = ((MenuRetievalModel)Session["model"]).name;
            model.phone = ((MenuRetievalModel)Session["model"]).phone;
            model.address = ((MenuRetievalModel)Session["model"]).address;
            model.Categories = ((MenuRetievalModel)Session["model"]).Categories;
            model.orderdate = (DateTime)Session["orderdate"];
            model.OrderType = ((MenuRetievalModel)Session["model"]).OrderType;
            model.ABN = ((MenuRetievalModel)Session["model"]).ABN;
            model.DataSetModifiers = ((MenuRetievalModel)Session["model"]).DataSetModifiers;
            Session["model"] = model;

            ModifierModel modon = model.GetNameOfModifierOn();
            model.forceModify(modon.BtnDesc, Convert.ToDecimal(modon.price));

            model.recallDetails();

            return PartialView("paymentdialog", (MenuRetievalModel)Session["model"]);
        }


    }
}

Mvc5MobileApplicationSG/Views/POSApp/About.cshtml
@{
    ViewBag.Title = "Spring Garden Chinese Restaurant Kambah";
}

<style>
    img.news-image {
        background: #dadada;
        height: 250px;
        width: 300px;
    }

    p.news-info {
        margin-top: 0;
    }

    .news-item {
        clear: both;
    }

    .odd div.news-info {
        float: right;
    }

    .odd div.news-image {
        float: left;
    }

    .even div.news-info {
        float: left;
    }

    .even div.news-image {
        float: right;
    }



    * {
        box-sizing: border-box;
    }

    /* Create two equal columns that floats next to each other */
    .columnLeft {
        float: left;
        width: 50%;
        padding: 10px;
        height: 300px; /* Should be removed. Only for demonstration */
    }

    .columnRight {
        float: right;
        width: 50%;
        padding: 10px;
        height: 300px; /* Should be removed. Only for demonstration */
    }

    /* Clear floats after the columns */
    .row:after {
        content: "";
        display: table;
    }
</style>


<h2>About</h2>


<p style="font-size: 15px">
    Spring Garden has been a well-established restaurant for over 10 years at Kambah Village.
    The restaurant has been developed as a family business where family members closely look after
    the establishment.
</p>

<p style="font-size: 15px">
    Iron chef Peter Lai has been working as a chef for the most prominent Chinese restaurants for over 40 years.
    He decided on establishing his own restaurant to spread his cooking to Canberra south side customers. His knowledge of
    Chinese cuisine is unrivalled in Canberra and most customers who has tasted his cuisines would no doubt agree.

</p>

<p class="news-info" style="font-size: 15px">
    The Chinese cuisines are a fusion of east meets west. These cuisines are standard Chinese dishes that most people would know, such as
    sweet and sour pork, roast duck, chicken cashews and the likes. We endeavour to meet and exceed expectations regarding the quality
    of the food presented with appetizing appeal.
</p>

<img class="news-image" src="~/Content/Chomolungma/images/image1.jpg" />
&nbsp;&nbsp;
<img class="news-image" src="~/Content/Chomolungma/images/image4.jpg" />
&nbsp;&nbsp;
<img class="news-image" src="~/Content/Chomolungma/images/image3.jpg" />
<br />

<!--
        <div class="row">
            <div class="columnLeft" style="background-color:green;">

            </div>
            <div class="columnRight" style="background-color:green;">

            </div>
        </div>
        <br />
        <br />
        <div class="row">
            <div class="columnLeft" style="background-color:green;">

            </div>
            <div class="columnRight" style="background-color:green;">

            </div>
        </div>
        <br />
        <br />
        <div class="row">
            <div class="columnLeft" style="background-color:green;">
                <div class="news-image">

                </div>
            </div>
            <div class="columnRight" style="background-color:green;">
                <div class="news-info">

                </div>
            </div>
        </div>

    -->

<br />
<br />
<p>- Spring Garden's Team -</p>

Mvc5MobileApplicationSG/Views/POSApp/Contact.cshtml
@{
    ViewBag.Title = "Bambusa Chinese Restaurant Manuka";
}


<style>

    .tg {
        border-collapse: collapse;
        border-spacing: 0;
    }

        .tg td {
            font-family: Arial, sans-serif;
            font-size: 14px;
            padding: 10px 5px;
            border-style: solid;
            border-width: 1px;
            overflow: hidden;
            word-break: normal;
            border-color: black;
        }

        .tg th {
            font-family: Arial, sans-serif;
            font-size: 14px;
            font-weight: normal;
            padding: 10px 5px;
            border-style: solid;
            border-width: 1px;
            overflow: hidden;
            word-break: normal;
            border-color: black;
        }

        .tg .tg-0lax {
            text-align: left;
            vertical-align: top
        }

    a:link {
        color: blue;
        background-color: transparent;
        text-decoration: none;
    }

    a:visited {
        color: pink;
        background-color: transparent;
        text-decoration: none;
    }

    a:hover {
        color: red;
        background-color: transparent;
        text-decoration: underline;
    }

    a:active {
        color: yellow;
        background-color: transparent;
        text-decoration: underline;
    }
</style>

<h2> Contact</h2>

<h5>
    Address
    <span> 36 Franklin St, Griffith ACT 2603, Canberra</span>
</h5>


<div>

    <h3>Deliveries start after 5:00pm each business day, online delivery service will be turned on at this time</h3>

    <iframe src="https://www.google.com/maps/embed?pb=!1m26!1m12!1m3!1d104100.9027689956!2d149.0561206121574!3d-35.376655841568144!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!4m11!3e6!4m3!3m2!1d-35.4418688!2d149.0944!4m5!1s0x6b164ce8b3f868c3%3A0x24f17f05160d7a30!2sbambusa%20chinese%20restaurant%20manuka!3m2!1d-35.319860299999995!2d149.1326243!5e0!3m2!1sen!2sau!4v1592406365238!5m2!1sen!2sau" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>


</div>

Mvc5MobileApplicationSG/Views/POSApp/ViewShoppingCart.cshtml
@model Mvc5MobileApplicationSG.Models.MenuRetievalModel


<button onclick="recallbill('@Model.name');">Shopping Cart</button>
<hiddenbutton id="paymentbutton" style="display: none;" data-toggle="modal" data-target="#paymentsummarymodal" onclick="'@Model.recallDetails()'" />

Mvc5MobileApplicationSG/Views/POSApp/declined.cshtml
@model Mvc5MobileApplicationSG.Models.MenuRetievalModel

@{
    ViewBag.Title = "declined";
}

<h3 style="color: red;">DECLINED</h3>

@if (@Model.approved == null || @Model.approved != "APPROVED")
{
    <label for="cardnumber" style="width:80px">Card number:</label>
    @Html.TextBoxFor(m => m.cardnumber, new { @required = "required" })
    <br />
    <label for="cardmonth" style="width:80px">Card expiry date:</label>
    @Html.DropDownListFor(m => m.cardexpirymonth, Model.MonthList, new { @id = "cardexpirymonthid" })
    @Html.DropDownListFor(m => m.cardexpiryyear, Model.YearList, new { @id = "cardexpiryyearid" })
    <p> (Month/Year)</p>
    <br />
    <label for="cardcvv" style="width:80px">Card cvv number:</label>
    @Html.TextBoxFor(m => m.cardcvv, new { @required = "required" })
    <br />

}
<br />
<div id="processing" style="display: none"><h5>processing please wait...</h5></div>
<button id="submitpayment" style="width: 100px; float: left;" class="btn btn-default" type="submit" onclick="return paymentclick();">Pay Card</button>
<button id="paymentclosedialog" style="width: 100px; float: right;" type="button" class="btn btn-default" data-dismiss="modal">Back</button>

Mvc5MobileApplicationSG/Views/POSApp/deliveryOffline.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>

    <script>

    function home() {
        // Now add markers
        var url = '@Url.Action("mainPage", "POSApp")'
        window.location = url;

    }

    </script>

</head>
<body>
    <div>
        <h1>Online Delivery is currently offline, please try again later on opening hours (see Contact page for details) 
            or call (02) 6296 3111 to make your order</h1>

        <button style="font-size: 15px;" onclick="home();">Back</button>



    </div>
</body>
</html>

Mvc5MobileApplicationSG/Views/POSApp/expiredSession.cshtml
@{
    ViewBag.Title = "expiredSession";
}

<script>

    function home() {
        // Now add markers
        var url = '@Url.Action("mainPage", "POSApp")'
        window.location = url;
        
    }

</script>

<body style="background-color: green;">

    <h1>Your session at POSApp Website has expired.</h1>

    <button style="font-size: 15px;" onclick="home();">POSApp Home Page</button>

</body>

Mvc5MobileApplicationSG/Views/POSApp/forceModify.cshtml
@model Mvc5MobileApplicationSG.Models.MenuRetievalModel
        
    
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                </div>
                <div class="modal-body">
                    @if (!Model.getDeliveryOn() && !Model.Debug)
                    {
                        <h1>Cloud Service Currently Offline please try again later. Please refresh your internet browser when trying again by closing and reopening this page.</h1>

                        <button id="hdclose" type="button" class="btn btn-default" data-dismiss="modal">Close</button>

                    }
                    else
                    {
                        using (Ajax.BeginForm("forceModify", "POSApp", null, new AjaxOptions { HttpMethod = "Post", UpdateTargetId = "items", OnSuccess = "OnSuccessModify" }, null))
                        {

                            <div id="deliverycontent">
                                <h4 class="modal-title">Force Modify</h4>

                                <p>Please enter details</p>
                                @for (int i = 0; i < Model.CurrentItemSelected().Modifiermodels.Count; i++)
                                {

                                    if (@Model.CurrentItemSelected().Modifiermodels[i].forced == "Y")
                                    {
                                        <label for="name">@Model.CurrentItemSelected().Modifiermodels[i].BtnDesc</label>
                                        @Html.RadioButtonFor(m => m.modBtnDesc, @Model.CurrentItemSelected().Modifiermodels[i].BtnDesc, new { @id = "radiobutton" })
                                    }


                                }

                            </div>
                            <br />
                            <input id="submitmodify" type="submit" value="Done" data-toggle="modal" data-target="#forcedmodifiermodal" />
                           
                            <br />


                        }

                    }
                </div>
            </div>



        </div>

Mvc5MobileApplicationSG/Views/POSApp/modify.cshtml
@model Mvc5MobileApplicationSG.Models.MenuRetievalModel



@if (!Model.getDeliveryOn() && !Model.Debug)
{
    <h1>Cloud Service Currently Offline please try again later. Please refresh your internet browser when trying again by closing and reopening this page.</h1>

    <button type="button" data-toggle="modal" data-target="#modifiermodal"> Close </button>

}
else
{
    using (Ajax.BeginForm("modify", "POSApp", null, new AjaxOptions { HttpMethod = "Post", UpdateTargetId = "items", OnSuccess = "modifysuccess" }, null))
    {

        <div id="deliverycontent">

            @if (@Model.CurrentItemSelected() != null)
            {
                @Html.DropDownListFor(m => m.modBtnDesc, @Model.CurrentItemSelected().getNonForcedModifiers(), new { @id = "modcode" })
                @Html.HiddenFor(m => m.itemno, @Model.itemno)
                @Html.HiddenFor(m => m.actualitemno, @Model.actualitemno)

            }

        </div>
        <br />
        <button id="submitmodifyitem" type="submit" data-toggle="modal" data-target="#paymentsummarymodal" > Add </button>
        <button type="button" data-toggle="modal" data-target="#paymentsummarymodal"> Close </button>
        <br />


    }

}

Mvc5MobileApplicationSG/Views/POSApp/paid.cshtml
@model Mvc5MobileApplicationSG.Models.MenuRetievalModel

@{
    ViewBag.Title = "paid";
}
<script>

    function refresh() {

        var url = '@Url.Action("mainPage", "POSApp")';

        window.location = url;

    }

</script>

<body>

   
    <h3>Your Order has been successfully paid, deliveries will be delivered within the 1 hour, pickups ready in 15 - 20 mins</h3>

        <button id="paymentsuccessclose" onclick="refresh();" type="button" class="btn btn-default" data-dismiss="modal">Close</button>



</body>

Mvc5MobileApplicationSG/Views/POSApp/paiddelivery.cshtml
@model Mvc5MobileApplicationSG.Models.MenuRetievalModel

@{
    ViewBag.Title = "paid";
}
<script>

    function refresh() {

        var url = '@Url.Action("mainPage", "POSApp")';

        window.location = url;

    }

</script>

<body>

    <h3>Your Order has been successfully paid, deliveries will be delivered within at least 1 hour, pickups ready in at least 30 mins</h3>

   <button id="paymentsuccessclose" onclick="refresh();" type="button" class="btn btn-default" data-dismiss="modal">Close</button>

</body>

Mvc5MobileApplicationSG/Views/POSApp/paymentdialog.cshtml
@model Mvc5MobileApplicationSG.Models.MenuRetievalModel

@{
    ViewBag.Title = "paymentdialog";
}


<script src="https://js.stripe.com/v3/"></script>
<script>

    function paid(amount) {

        var url = '@Url.Action("payment", "POSApp")';

    $.ajax({
        url: url,
        type: "GET",
        data: { amount: amount },
        success: function (results) {
            return true;

        },
        error: function (jqXHR, textStatus, errorThrown) {
            alert(jqXHR.status);
            alert(textStatus);
            alert(errorThrown);
        },


    });
        return false;

    }




    function paymentclick(amount) {

        var clientSecret = "";

    hidden();
    var url = '@Url.Action("pay", "POSApp")';

    $.ajax({
        url: url,
        type: "GET",
        datatype: "JSON",
        contentType: "application/json;charset=utf-8",
        data: { amount: amount },
        success: function (results) {

             clientSecret = results.clientsecret;
           // alert(ClientSecret);
        stripe.confirmCardPayment(clientSecret, {
            payment_method: {
                card: card
            }
        }).then(function (result) {

            if (result.error) {
                // Show error to your customer (e.g., insufficient funds)
                showAll();
                alert("Declined Transaction, please try agagin");
                console.log(result.error.message);
            } else {

                // The payment has been processed!
                if (result.paymentIntent.status === 'succeeded') {
                    paid(amount);
                    alert("Succeeded payment\n\nYour Order has been successfully paid, deliveries will be delivered within the 1 hour, pickups ready in 30 mins");
                    var backButton = document.getElementById("paymentclosedialog");
                    backButton.click();
                    location.reload();
                    // Show a success message to your customer
                    // There's a risk of the customer closing the window before callback
                    // execution. Set up a webhook or plugin to listen for the
                    // payment_intent.succeeded event that handles any business critical
                    // post-payment actions.
                }
            }
        });


        },
        error: function (jqXHR, textStatus, errorThrown) {
            alert(jqXHR.status);
            alert(textStatus);
            alert(errorThrown);
        },

    });


        return false;


    }

    function hidden() {

         $.ajaxSetup({
    beforeSend:function(){
        // show gif here, eg:
                 $("#processing").show();
                  $('#submitpayment').hide();
        $('#paymentclosedialog').hide();
    },
    complete:function(){
        // hide gif here, eg:
         $('#submitpayment').hide();
        $('#paymentclosedialog').hide();
    }
});


    }

    function show() {

        $.ajax({
            success: function () {
                // do something

                var paymentclosebutton = document.getElementById("paymentclosedialog");
                paymentclosebutton.style.display = "block";

                var processingbar = document.getElementById("processing");
                processingbar.style.diplay = "none";


            }
        });
    }


    function showAll() {

        $('#submitpayment').show();
        $('#paymentclosedialog').show();
        $("#processing").hide();

    }

    // A reference to Stripe.js initialized with your real test publishable API key.
    var stripe = Stripe("pk_live_yXxKTaVfdkgQQ3xyaCK8sXGp00D9nErvsC");
 //   var stripe = Stripe("pk_test_51GuFRFGSzY6XVzcspooKuyVIwxLpm8gUu6MILROJei6FrtEegl0XnI7H1mN2ydKenuyjfe2kOpK2wVVgHjLmKYwL00X9ed1Bax");

// The items the customer wants to buy

    var elements = stripe.elements();



var form = document.getElementById('payment-form');


  var style = {
  base: {
    color: "#32325d",
  }
};

var card = elements.create("card", { style: style });
card.mount("#card-element");


    card.on('change', ({error}) => {
  const displayError = document.getElementById('card-errors');
  if (error) {
    displayError.textContent = error.message;
  } else {
    displayError.textContent = '';
  }
    });



</script>

<hiddeninput id="clientsecret" value="@ViewData["ClientSecret"]" />
<form id="payment-form">
    <div id="total" style="left: initial; margin-left: 1%">

        @{
            double total = 0;
            var suburb = "";

            if (Model != null && Model.RecallItems != null)
            {
                <ul>
                    @for (int i = 0; i < Model.RecallItems.Count; i++)
                    {

                        if (Model.RecallItems[i].discountflag == null || Model.RecallItems[i].discountflag == "" || Model.RecallItems[i].discountflag == "N")
                        {

                            if (!@Model.RecallItems[i].isSpecial())
                            {
                    <li style="font-size: 10px">
                        <button style="align-self:center; font-size: 10px; color: white; background: green;" onclick="return updateQty('add', '@Model.RecallItems[i].getinputboxstr()', '@Model.RecallItems[i].itemno')">+</button><input style="width: 30px; font-size: 10px; color: black;" type="button" value="@Model.RecallItems[i].itemqty" /><button style="align-self:center; font-size: 10px; color: white; background: green;" onclick="return updateQty('deduct', '@Model.RecallItems[i].getinputboxstr()', '@Model.RecallItems[i].itemno')">-</button> $@String.Format("{0:0.00}", @Math.Round(@Model.RecallItems[i].itemprice, 2)) @Model.RecallItems[i].itemname.Trim().ToUpper()

                        @if (@Model.CurrentItemSelected(@Model.RecallItems[i].actualitemno).getNonForcedModifiers().Count() > 0 && @Model.RecallItems[i].itemqty == 1)
                        {
                            <!--        <button type="button" style="align-self:center; font-size: 10px; color: white; background: green;" onclick="return modify('@Model.RecallItems[i].itemno', '@Model.RecallItems[i].actualitemno')"> Modify </button>
                            <button style="visibility: hidden;" id="modifybutton" data-toggle="modal" data-target="#modifiermodal"></button> -->
                        }

                    </li>

                            }
                            else
                            {
                                <li style="font-size: 10px">
                                    @Model.RecallItems[i].itemqty X $@String.Format("{0:0.00}", @Math.Round(@Model.RecallItems[i].itemprice, 2)) @Model.RecallItems[i].itemname.Trim().ToUpper()
                                </li>
                            }

                            <br />
                        }
                        else
                        {
                            suburb = @Model.RecallItems[i].itemname.Trim() + " at " + "$" + @String.Format("{0:0.00}", @Math.Round(@Model.RecallItems[i].itemprice, 2));

                        }



                        total = total + @Model.RecallItems[i].itemqty * @Model.RecallItems[i].itemprice;
                    }
                </ul>
                <p>---------------------------------------------</p>
                <h5>@suburb</h5>

                <h2>Sub Total: $@String.Format("{0:0.00}", @Math.Round(total, 2))</h2>
                <p>---------------------------------------------</p>
            }
            else
            {
                <h3>No Items Selected Yet</h3>
            }

        }

        @if ((total >= 30 && Model.OrderType == "homedelivery") || Model.OrderType == "takeaway")
        {
            <h5>Please enter credit card details below:</h5>
            <div id="card-element">
                <!-- Elements will create input elements here -->
            </div>

            <!-- We'll put the error messages in this element -->
            <div id="card-errors" role="alert"></div>

            <br />
            <br />
            <div id="processing" style="display: none"><h5>processing please wait...</h5></div>
            <button id="submitpayment" data-secret="@ViewData["ClientSecret"]" style="width: 100px; float: left;" class="btn btn-default" type="submit" onclick="return paymentclick('@String.Format("{0:0.00}", @Math.Round(total, 2))');">Pay Card</button>
            <button id="paymentclosedialog" style="width: 100px; float: right;" type="button" class="btn btn-default" data-dismiss="modal">Back</button>

            
        }
        else
        {

            <h3>Home delivery orders must be minimum $30</h3>
            <button id="paymentclosedialog" type="button" class="btn btn-default" data-dismiss="modal">Back</button>


        }

        <br />


    </div>

</form>

Mvc5MobileApplicationSG/Views/POSApp/shutDown.cshtml
    <p>
        TO OUR VALUED CUSTOMERS & FRIENDS
        It is with a heavy heart to announce that Spring Gardens will be temporarily closing the doors starting next week Monday  30th March 2020. We have been working around the clock to explore every possible solution but in the end the health of our staff and customers comes first. This is the hardest test we have ever faced in the last 15 years at Spring Gardens but we are very determined to get back to doing what we love as soon as it is safe to do so.

        Stay safe. We can get through this together.

        #socialdistance #flattenthecurve #supportyourlocal #wewillbeback #watchthisspace

    </p>